<? include "header.phtml"; ?>
<? include "menubaradmin.phtml"; ?>
<?// include "barkanan.phtml"; ?>
       <div id="contentadmin">
        <h1>Ubah Data Kelola Kearsipan</h1>
			<form action="<? echo $this->basePath;?>/home/index/simpanarsipedit?id_data_arsip=<?php echo $this->hasil->id_data_arsip;?>" method="post">
			  <div class="form_settings">
				<input type="hidden" name="id_data_arsip" value="<?php echo $this->hasil->id_data_arsip;?>"/>
				NIK :<br>
				<input type="text" name="nik" value="<?php echo $this->hasil->nik;?>"/>
										
				<br><br>Nama Surat :<br>
				<select  name="nama_surat" >
				<option value="<?php echo $this->hasil->nama_surat;?>"><?php echo $this->hasil->nama_surat;?></option>
				<?php foreach($this->surat as $data) : ?>
					<option value="<?php echo $this->escape($data->nama_surat);?>"><?php echo $this->escape($data->nama_surat);?></option>
				<?php endforeach; ?>				
				</select>
				
				<br><br>No. Surat :<br>
				<input type="text" name="no_surat" value="<?php echo $this->hasil->no_surat;?>" required />
				
				<br><br>Tanggal Surat :<br>
				<input type="text" name="tanggal_surat" value="<?php echo $this->hasil->tanggal_surat;?>" required/>
				
				<br><br>Ruangan :<br>
				<input type="text" name="ruangan" value="<?php echo $this->hasil->ruangan;?>" required/>
				
				<br><br>Lemari :<br>
				<input type="text" name="lemari" value="<?php echo $this->hasil->lemari;?> " required/>
				
				<br><br>Rak :<br>
				<input type="text" name="rak" value="<?php echo $this->hasil->rak;?>" required/>
				
				<br><br>Kotak :<br>
				<input type="text" name="kotak" value="<?php echo $this->hasil->kotak;?>" required/>
				
				<br><br>Data File :<br>
				<input type="file" name="data_file" value="" placeholder="Masukan data_file" required/>
				
				
				<br><br><p style="padding-top: 15px"><span>&nbsp;</span>
				
				<input class="button" type="submit" name="Ubah" value="Ubah" />
				<input class="reset" type="reset" name="reset" value="Ulangi" />
				<input action="action" class="kembali"  value="Kembali" onclick="history.go(-1);" />
				
				</p>
			  </div>
			</form><br><br></center>
      </div>
	 </div>
	
   <?include "footer.phtml"; ?>