<? include "header.phtml"; ?>
<?php 
	if($this->id_jenis_pengguna == '1'){
		include "menubaradmin.phtml";
	}else{
		include "menubarpemberdayaan.phtml";	
	}
?>
      <div class="content">
        <h1>Data Kelola Arsip</h1>
		<?php // peringatan/ notifikasi
				if($this->peringatan)
				echo $this->peringatan;
		?>
		
		<form action="<? echo $this->basePath;?>/home/index/arsipcari" method="post">
		<div class="form_settings2">
				<input type="text" name="cariarsip" placeholder="Masukan Pencarian"/>
				<input class="submit" type="submit" name="cari" value="cari" />
			 </div>
		</form><br>
		
		<form action="<? echo $this->basePath;?>/home/index/arsiptambah" method="post">
		<div class="form_settings2">
				<button class="button">tambah arsip</button>
			 </div>
		</form><br>
		
		<table style="width:100%; border-spacing:0;" id="rounded-corner">
          <tr align ="center">
			  <th>Nama</th>
			  <th>Nama Surat</th>
			  <th>No.Surat</th>
			  <th>Tanggal Surat</th>
			  <th>Ruangan</th>
			  <th>Lemari</th>
			  <th>Rak</th>
			  <th>Kotak</th>
			  <th>Data Arsip</th>			  
			  <th colspan=2>Aksi</th>
		  </tr>
		  <?php $i=1; foreach($this->arsip as $data) : ?>
			<tr>
            <td><?php echo $this->escape($data->nama);?></td>
            <td><?php echo $this->escape($data->nama_surat);?></td>
            <td><?php echo $this->escape($data->no_surat);?></td>
            <td><?php $tanggal_surat = date('d-m-Y', strtotime($data->tanggal_surat));
					echo $this->escape($tanggal_surat);?></td>
            <td><?php echo $this->escape($data->ruangan);?></td>
            <td><?php echo $this->escape($data->lemari);?></td>
            <td><?php echo $this->escape($data->rak);?></td>
            <td><?php echo $this->escape($data->kotak);?></td>
            <td><a class="tooltip" href="<?php echo $this->basePath; ?>/home/index/arsipdownload?id_data_arsip=<? echo $data->id_data_arsip;?>"><img src="<? echo $this->basePath;?>/icon/open131.png" alt="" width="32px" height="32px" title="lihat" border="0" /><span><b></b> lihat arsip</span></a></td>
			
            <td><a href="<?php echo $this->basePath; ?>/home/index/arsipedit?id_data_arsip=<?php echo $this->escape($data->id_data_arsip);?>"><img src="<? echo $this->basePath;?>/images/user_edit.png" alt="" title="edit" border="0" /></a></td>
            <td><a href="<?php echo $this->basePath; ?>/home/index/arsiphapus?id_data_arsip=<?php echo $this->escape($data->id_data_arsip);?>" class="ask" ><img src="<? echo $this->basePath;?>/images/trash.png" alt="" title="hapus" border="0" /></a></td>		
        </tr>
		<?php $i++; endforeach; ?>
          
        </table>
		<?php
		$jumPage = ceil($this->jumData/$this->dataPerPage);

		// menampilkan link previous
		?>
		<div class="pagination">
		<center>
		<?php
		if ($this->noPage > 1) {
		?>
		<a class="page gradient" href="<?php echo $this->basePath;?>/home/index/arsipdata?page= <?php echo ($this->noPage-1);?>">&lt;&lt; Prev</a>
		<?php
		}

		// memunculkan nomor halaman dan linknya

		 
		for($page = 1; $page <= $jumPage; $page++)
		{
			if ((($page >= $this->noPage - 3) && ($page <= $this->noPage + 3)) || ($page == 1) || ($page == $jumPage))
			{
				if (($showPage == 1) && ($page != 2))  echo "...";

				if (($showPage != ($jumPage - 1)) && ($page == $jumPage))  echo "...";

				if ($page == $this->noPage) echo " <div class='page active'>".$page."</div> ";

				else{
					?>
					<a class="page gradient" href="<?php echo $this->basePath;?>/home/index/arsipdata?page=<?php echo $page; ?>"><?php echo $page; ?> </a>
					<?php
				}
				

				$showPage = $page;

			}

		}

		// menampilkan link next
		if ($this->noPage < $jumPage){
		?>
		
		<a class="page gradient" href="<?php echo $this->basePath;?>/home/index/arsipdata?page=<?php echo ($this->noPage+1);?>">Next &gt;&gt;</a>
		<?php
		}
		?>
		</center>
      </div>
		
		
      </div>
	 </div>
	
   <?include "footer.phtml"; ?>