<? include "header.phtml"; ?>
<? include "menubaradmin.phtml"; ?>
<?// include "barkanan.phtml"; ?>
       <div id="contentadmin">
        <h1>Tambah Data Kelola Kearsipan</h1>
			<form id="form1" action="<? echo $this->basePath;?>/home/index/simpanarsip" method="post" enctype="multipart/form-data">
			  <div class="form_settings">				
				NIK :<br>
				<input type="text" name="nik" placeholder="Masukan NIK" required/>
										
				<br><br>Nama Surat :<br>
				<select  name="nama_surat" required>
				<option selected="selected">--Nama Surat--</option>
				<?php foreach($this->surat as $data) : ?>
					<option value="<?php echo $this->escape($data->nama_surat);?>"><?php echo $this->escape($data->nama_surat);?></option>
				<?php endforeach; ?>				
				</select>
				
				<br><br>No. Surat :<br>
				<input type="text" name="no_surat" placeholder="Masukan Nomor Surat" required/>
				
				<br><br>Tanggal Surat :<br>
				<input type="text" class="tanggal" name="tanggal_surat" placeholder="Masukan Tanggal Surat" required/>
				
				<br><br>Ruangan :<br>
				<input type="text" name="ruangan" placeholder="Masukan Nama Ruangan " required/>
				
				<br><br>Lemari :<br>
				<input type="text" name="lemari" placeholder="Masukan Lemari Surat" required/>
				
				<br><br>Rak :<br>
				<input type="text" name="rak" placeholder="Masukan Rak Surat" required/>
				
				<br><br>Kotak :<br>
				<input type="text" name="kotak" placeholder="Masukan Kotak Surat" required/>
				
				<br><br>Data File :<br>
				<input type="file" name="data_file" placeholder="Masukan data_file" required/>
				
				<p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="simpan" value="Simpan" /></p>
			  </div>
			</form><br><br></center>
      </div>
	 </div>
	
   <?include "footer.phtml"; ?>