<? include "header.phtml"; ?>
<? include "menubartantrib.phtml"; ?>
<?// include "barkanan.phtml"; ?>
	<?php
		//echo $this->datauser->nama_pengguna;
	?>
      <div id="contentadmin">
        <h1><u><b><?php echo "Halaman ". $this->jenispengguna->nama_jenis_pengguna;?></b></u></h1>
         <? include "profilketua.phtml"; ?>
		<table style="width:100%; border-spacing:0;">
          <tr align ="center">
			  <th>No</th>
			  <th>No Surat</th>
			  <th>Tgl Surat</th>
			  <th>NIK</th>
			  <th>Nama Warga</th>
			  <th>RT / RW</th>
			  <th>Keperluan</th>
			  <th colspan=3>Aksi</th>
		  </tr>
		 <?php $i=1; foreach($this->permintaan as $data) : ?>
		 
			<tr>
			<td><?php echo $i;?></td>		
            <td><?php echo $this->escape($data->no_surat);?></td>
            <td><?php echo $this->escape($data->tanggal_surat);?></td>
            <td><?php echo $this->escape($data->nik);?></td>
            <td><?php echo $this->escape($data->nama);?></td>
            <td><?php echo $this->escape($data->rt);echo "/";echo $this->escape($data->rw);?></td>
            <td><?php echo $this->escape($data->keperluan);?></td>
           
			
			
            
			<?php if($data->status==0){ ?>
            <td><a href="<?php echo $this->basePath; ?>/home/index/bdaccedit?id_permintaan=<?php echo $this->escape($data->id_permintaan_bd);?>">ACC</a></td>
			<?php }else{ ?>
			<td><img src="<? echo $this->basePath;?>/images/valid.png" alt="" title="" border="0" /></td>
			<?php } ?>
            
		
			
        </tr>
			
		<?php $i++; endforeach; ?>
        </table>
		<?php
		$jumPage = ceil($this->jumData/$this->dataPerPage);

		// menampilkan link previous
		?>
		<div class="pagination">
		<center>
		<?php
		if ($this->noPage > 1) {
		?>
		<a class="page gradient" href="<?php echo $this->basePath;?>/home/index/bd?page= <?php echo ($this->noPage-1);?>">&lt;&lt; Prev</a>
		<?php
		}

		// memunculkan nomor halaman dan linknya

		 
		for($page = 1; $page <= $jumPage; $page++)
		{
			if ((($page >= $this->noPage - 3) && ($page <= $this->noPage + 3)) || ($page == 1) || ($page == $jumPage))
			{
				if (($showPage == 1) && ($page != 2))  echo "...";

				if (($showPage != ($jumPage - 1)) && ($page == $jumPage))  echo "...";

				if ($page == $this->noPage) echo " <b>".$page."</b> ";

				else{
					?>
					<a class="page gradient" href="<?php echo $this->basePath;?>/home/index/bd?page=<?php echo $page; ?>"><?php echo $page; ?> </a>
					<?php
				}
				

				$showPage = $page;

			}

		}

		// menampilkan link next
		if ($this->noPage < $jumPage){
		?>
		
		<a class="page gradient" href="<?php echo $this->basePath;?>/home/index/bd?page=<?php echo ($this->noPage+1);?>">Next &gt;&gt;</a>
		<?php
		}
		?>
		</center>
      </div>
	 </div>
	
   <?include "footer.phtml"; ?>