<? include "header.phtml"; ?>
<?php 
	if($this->id_jenis_pengguna == '1'){
		include "menubaradmin.phtml";
	}else{
		include "menubarpemberdayaan.phtml";	
	}
?>
       <div id="contentadmin">
        <h1>Tambah Berita</h1>
			<form id="form1" action="<? echo $this->basePath;?>/home/index/simpanberita" method="post" enctype="multipart/form-data">
			  <div class="form_settings">				
				Judul Berita :<br>
				<input type="text" name="judul_berita" value="" required/>
				
				<br>Isi Berita:<br>
				<textarea name="isi_berita" required></textarea>
				
				<p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="simpan" value="Simpan" /></p>
			  </div>
			</form>
      </div>
	 </div>
	
   <? include "footer.phtml"; ?>