<? include "header.phtml"; ?>
<? include "menubaradmin.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div class="content">
        <h1>Data Surat</h1>
		<table style="width:100%; border-spacing:0;" id="rounded-corner">
          <tr align ="center">
			  <th>Nomor</th>
			  <th>Nama Surat</th>
			  <th>Jenis Surat</th>
			  <th colspan=2>Aksi</th>
		  </tr>
		  <?php $i=1; foreach($this->surat as $data) : ?>
			<tr>
			<td><?php echo $i;?></td>	
			<td><?php echo $this->escape($data->nama_surat);?></td>	
            <td><?php echo $this->escape($data->nama_jenis_surat);?></td>
           
			
			
            <td><a href="<?php echo $this->basePath; ?>/home/index/suratedit?id_surat=<?php echo $this->escape($data->id_surat);?>" title="edit"><img src="<? echo $this->basePath;?>/images/user_edit.png" alt="" title="" border="0" /></a></td>
            <td><a href="<?php echo $this->basePath; ?>/home/index/surathapus?id_surat=<?php echo $this->escape($data->id_surat);?>" title="delete" class="ask"><img src="<? echo $this->basePath;?>/images/trash.png" alt="" title="" border="0" /></a></td>
		
			
        </tr>
		<?php $i++; endforeach; ?>
          
        </table>
      </div>
	 </div>
	
   <?include "footer.phtml"; ?>