<? include "header.phtml"; ?>
<? include "menubarpemberdayaan.phtml"; ?>
<?// include "barkanan.phtml"; ?>
	<?php
		//echo $this->datauser->nama_pengguna;
	?>
      <div id="contentadmin">
        <h1><u><b><?php echo "Halaman ". $this->jenispengguna->nama_jenis_pengguna;?></b></u></h1>
        <b><?php echo "Kelurahan ". $this->kelurahan->nama_kelurahan;?></b>
        <h2>Permintaan Surat yang Belum ACC</h2>
        <h4><?php echo $this->surat; ?></h4>
		<table style="width:100%; border-spacing:0;" id="rounded-corner">
          <tr align ="center">
			  <th>No</th>
			  <th>No Surat</th>
			  <th>Tgl Surat</th>
			  <th>NIK</th>
			  <th>Nama Warga</th>
			  <th>RT / RW</th>
			  <th>No. KIP</th>
			  <th colspan=3>Aksi</th>
		  </tr>
		 <?php $i=1; foreach($this->permintaan as $data) : ?>
		 
			<tr>
			<td><?php echo $i;?></td>		
            <td><?php echo $this->escape($data->no_surat);?></td>
            <td><?php echo $this->escape($data->tanggal_surat);?></td>
            <td><?php echo $this->escape($data->nik);?></td>
            <td><?php echo $this->escape($data->nama);?></td>
            <td><?php echo $this->escape($data->rt);echo "/";echo $this->escape($data->rw);?></td>
			<td></td>
           
			
			<?phpif($this->escape($data->status)==0){ ?>
            <td><a href="<?php echo $this->basePath; ?>/home/index/accedit?id_permintaan=<?php echo $this->escape($data->id_permintaan);?>"></a>ACC</td>
			<?php }else{?>
			<img src="<? echo $this->basePath;?>/images/valid.png" alt="" title="ACC Permintan ini" border="0" />
			<?php }?>
            
		
			
        </tr>
		<?php $i++; endforeach; ?>
          
        
	
          
        </table>
      </div>
	 </div>
	
   <?include "footer.phtml"; ?>