<? include "header.phtml"; ?>
<? require_once "menubar.phtml"; ?>
<? //include "barkanan.phtml"; ?>
      <div class="content">
		
        <h1>Selamat Datang di Sistem Manajemen Kelurahan</h1>
		
		<div class="card">
		<div class="ket">Profile</div>
			<p>Nama Petugas <t> :<?php echo $this->pengguna->nama_pengguna?> </p>
			<p>Kelurahan    :<?php echo $this->pengguna->nama_kelurahan?> </p>
			<p>NIP Petugas  :<?php echo $this->pengguna->nip_pengguna?></p>
			<p>Jabatan      :<?php echo $this->pengguna->jabatan?></p>
			<p>Alamat       :<?php echo $this->pengguna->alamat?></p>
			<p>Nomor Telp   :<?php echo $this->pengguna->no_telp?></p>			
		</div>	
          <h4>Kontak Pusat</h4>
		  <table class="kosong">
			<tr>
				<td>Telepon</td>
				<td>:</td>
				<td>0857-8221-3794</td>
			</tr>
			<tr>
				<td>E-mail</td>
				<td>:</td>
				<td>ratihpujihati@student.upi.edu</td>
			</tr>
			<tr>
				<td>Twitter</td>
				<td>:</td>
				<td>Ratih</td>
			</tr>
			<tr>
				<td>Facebook</td>
				<td>:</td>
				<td>Ratih</td>
			</tr>
		  </table>
        
      </div>
   <? include "footer.phtml"; ?>
