<? include "header.phtml"; ?>
<? include "menubarketua.phtml"; ?>
<?// include "barkanan.phtml"; ?>
	<?php
		//echo $this->datauser->nama_pengguna;
	?>
      <div id="contentadmin">
        <h2><u><b><?php echo "Halaman ". $this->jenispengguna->nama_jenis_pengguna;?></b></u></h2>
        <b><?php echo "Kelurahan ". $this->kelurahan->nama_kelurahan;?></b>
        <h1>Permintaan Surat Sudah ACC</h1>
		<table style="width:100%; border-spacing:0;">
          <tr align ="center">
			  <th>No</th>
			  <th>No Surat</th>
			  <th>Tgl Surat</th>
			  <th>NIK</th>
			  <th>Nama Warga</th>
			  <th>RT / RW</th>
			  <th>No. KIP</th>
			  <th>Keterangan</th>
			  <th >Aksi</th>
		  </tr>
		<?php $i=1; foreach($this->datapermintaan as $data) : ?>
			<tr>
			<td><?php echo $i;?></td>	
			<td><?php echo $this->escape($data->nomor_surat);?></td>	
            <td><?php echo $this->escape($data->tgl_surat);?></td>
            <td><?php echo $this->escape($data->nik);?></td>
            <td><?php echo $this->escape($data->nama_lengkap);?></td>
            <td><?php echo $this->escape($data->rt);echo "/".$this->escape($data->rw);?></td>
			<td></td>
			<td><?php echo "Surat ". $this->escape($data->nama_surat);?></td>
			
			
            <td><a href="<?php echo $this->basePath; ?>/home/index/cabutaccedit?id_permintaan=<?php echo $this->escape($data->id_permintaan);?>"><img src="<? echo $this->basePath;?>/images/user_logout.png" alt="" title="Tutup Permintan ini" border="0" /></a></td>
            
		
			
        </tr>
		<?php $i++; endforeach; ?>
          
        
	
          
        </table>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>