<? include "header.phtml"; ?>
<? require_once "menubar.phtml"; ?>
<? //include "barkanan.phtml"; ?>
      <div class="content">
		
        <h1>Selamat Datang di Sistem Manajemen Kinerja Kelurahan</h1>
		
			<div class="card">
				<div class="judul">Profil Pengguna</div>			
				<div class="isi ">					
					<p>Nama: <b> <?php echo $this->pengguna->nama_pengguna ?></b></p>
						<p>Kelurahan:</strong> <b><?php echo $this->pengguna->nama_kelurahan ?></b></p>
						<p>Nip: <b><?php echo $this->pengguna->nip_pengguna ?></b></p>
						<p>Jabatan:<b> <?php echo $this->pengguna->jabatan ?></b></p>
						<p>Alamat: <b><?php echo $this->pengguna->alamat ?></b></p>
						<p>Nomor Telp :<b> <?php echo $this->pengguna->no_telp ?></b></p>
						<a href="<? echo $this->basePath;?>/surat/index/penggunaedit?id_pengguna=<?php echo $this->pengguna->id_pengguna;?>"><button  class="modal">Edit</button></a>
				</div>				
			</div>				
		
		
          <h4>Kontak Pusat</h4>
		  <table class="kosong">
			<tr>
				<td>Telepon</td>
				<td>:</td>
				<td>0857-8221-3794</td>
			</tr>
			<tr>
				<td>E-mail</td>
				<td>:</td>
				<td>ratihpujihati@student.upi.edu</td>
			</tr>
			<tr>
				<td>Twitter</td>
				<td>:</td>
				<td>Ratih</td>
			</tr>
			<tr>
				<td>Facebook</td>
				<td>:</td>
				<td>Ratih</td>
			</tr>
		  </table>
        
      </div>
   <? include "footer.phtml"; ?>
