<? include "header.phtml"; ?>
<? require_once "menubar.phtml"; ?>
<? //include "barkanan.phtml"; ?>
      <div class="content">
		
        <h1>Selamat Datang di Sistem Manajemen Kelurahan</h1>
		
		<div class="card">
		<div class="ket">Profile</div>
			<table>
				<tr>
					<td>Nama Petugas</td>
					<td>:</td>
					<td><?php echo $this->pengguna->nama_pengguna?></td>
				</tr>
				<tr>
					<td>Kelurahan</td>
					<td>:</td>
					<td><?php echo $this->pengguna->nama_kelurahan?></td>
				</tr>
				
				<tr>
					<td>NIP Petugas</td>
					<td>:</td>
					<td><?php echo $this->pengguna->nip_pengguna?></td>
				</tr>
			</table>
		</div>	
          <h4>Kontak Pusat</h4>
		  <table class="kosong">
			<tr>
				<td>Telepon</td>
				<td>:</td>
				<td>0857-8221-3794</td>
			</tr>
			<tr>
				<td>E-mail</td>
				<td>:</td>
				<td>m.ade@student.upi.edu</td>
			</tr>
			<tr>
				<td>Twitter</td>
				<td>:</td>
				<td>madelhaq</td>
			</tr>
			<tr>
				<td>Facebook</td>
				<td>:</td>
				<td>madelhaq</td>
			</tr>
		  </table>
        
      </div>
	 </div>
   <? include "footer.phtml"; ?>
