<!DOCTYPE HTML>
<html>

<head>
  <title>Sistem Informasi Kinerja Pelayanan Kelurahan</title>
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <link rel="stylesheet" type="text/css" href="<? echo $this->basePath;?>/login/css/style.css" />
  
  <link rel="icon" href="<? echo $this->basePath;?>/login/logo/cimahi.png" type="image/png">
 
</head>

<body>  
	<img class="logo" src="<? echo $this->basePath;?>/login/logo/cimahi.png"/>
    <span href="#" class="button" id="toggle-login">SIM Kinerja Pelayanan <br />Kelurahan Leuwigajah</span>
    
	<div id="login">
	
		<h1>Silakan Login</h1>	
			<?php if($this->peringatan)
				echo "<div class='peringatan'>".$this->peringatan."</div>";
			?>
			
			<form action="<? echo $this->basePath;?>/home/index/home" method="post" autocomplete="off">
			 	<input type="text" name="username" value="" placeholder="masukan username" required />
				<input type="password" name="password" value="" placeholder="masukan password" required/>
				<p><span>&nbsp;</span><input class="submit" type="submit" name="name" value="login" title="Klik jika sudah mengisi username dan password"/></p>
			 </form>				
    </div>
    <footer>
      <p>Sistem Informasi Kinerja Pelayanan Kelurahan Pemerintah Kota Cimahi <?php echo date(Y)?></p>
    </footer> 
  
  <!-- javascript at the bottom for fast page loading -->
  <script src="<? echo $this->basePath;?>/login/js/index.js"></script>
  
  <script src='<? echo $this->basePath;?>/login/js/js.js'></script>
</body>

</html>
