<!DOCTYPE HTML>
<html>

<head>
  <title>SIM Kelurahan</title>
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <link rel="stylesheet" type="text/css" href="<? echo $this->basePath;?>/login/css/style.css" />
 
</head>

<body>  
    <span href="#" class="button" id="toggle-login">SIM Kelurahan Leuwi Gajah</span>
    
	<div id="login">
		<div id="triangle"></div>
		<h1>Silakan Login</h1>		
			<form action="<? echo $this->basePath;?>/home/index/home" method="post" autocomplete="off">
			 	<input type="text" name="username" value="" placeholder="masukan username" />
				<input type="password" name="password" value="" placeholder="masukan password"/>
				<p><span>&nbsp;</span><input class="submit" type="submit" name="name" value="login" title="Klik jika sudah mengisi username dan password"/></p>
			 </form>		
    </div>
    <footer>
      <p>Sistem Informasi Manajemen Kelurahan Pemerintah Kota Cimahi <?php echo date(Y)?></p>
    </footer> 
  
  <!-- javascript at the bottom for fast page loading -->
  <script src="<? echo $this->basePath;?>/login/js/index.js"></script>
  
  <script src='<? echo $this->basePath;?>/login/js/js.js'></script>
</body>

</html>
