<? include "header.phtml"; ?>
<? include "menubaradmin.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div class="content">
        <h1>Edit Jenis Pengguna</h1>
			<form action="<? echo $this->basePath;?>/home/index/simpanjenispenggunaedit?id_jenis_pengguna=<?php echo $this->jenispengguna->id_jenis_pengguna;?>" method="post">
			  <div class="form_settings">
				</select>
				<br><br>Nama Jenis Pengguna :<br>
				<input type="text" name="nama_jenis_pengguna" value="<?php echo $this->jenispengguna->nama_jenis_pengguna;?>" />
				<br><br><p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="name" value="ubah" /></p>
			  </div>
			</form><br><br></center>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>