<? include "header.phtml"; ?>
<?php 
	if($this->id_jenis_pengguna == '1'){
		include "menubaradmin.phtml";
	}else{
		include "menubarpemberdayaan.phtml";	
	}
?>
  <div id="contentadmin">
  <h1>Cetak Data Layanan Per Petugas Layanan</h1>
	
	<input id="tab1" type="radio" name="tabs" checked>
	<label for="tab1">Laporan Per Periode</label>

	<section id="content1">
    <h3 align="center">Silakan Pilih Periode dan Petugas</h3>
	<p>
	<!--Laporan perhari -->
		<div class="form_settings2" align="center">
			<form action="<? echo $this->basePath;?>/home/index/laporanperpetugas" method="post">	
				<select name="tanggal">
				<option value="0" selected="selected">Tanggal</option>
				<?php
				for($i=1; $i<=31; $i+=1){
					if($i < 10){
						$i = "0".$i;
					}else{
						$i;
					}
					echo"<option value=$i> $i </option>";
				}
				?>
				</select>
				<select name="bln">
				<option value="0" selected="selected">Bulan</option>
				<?php
				$bulan_ind=array("Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember");
				$bulan=array("January","February","March","April","May","June","July","August","September","October","November","December");
				$jlh_bln=count($bulan_ind);
				for($c=0; $c<$jlh_bln; $c+=1){
					echo"<option value=$bulan[$c]> $bulan_ind[$c] </option>";
				}
				?>
				</select>
				<select name="thn">
				<option value="0" selected="selected">Tahun</option>
				<?php
				for($i=date('Y'); $i>=2010; $i-=1){
				echo"<option value=$i> $i </option>";
				}
				?>
				</select>
				<select name="petugas">
					<option selected="selected">Petugas</option>				
					<?php $i=1; foreach($this->petugas as $data) : ?>
					<option value="<?php echo $this->escape($data->id_pengguna);?>"> <?php echo $this->escape($data->nama_pengguna);?></option>
					<?php $i++; endforeach; ?>
				</select>
		</p>			
			<p>
				<button class="cetak" align="center">Cetak</button>
			</p>
			</form>	
		<hr>
		<i>Keterangan :</i><br/>
		<i>Pilih Tanggal, Bulan, dan Tahun untuk Laporan Harian</i><br/>
		<i>Pilih Bulan, dan Tahun untuk Laporan Bulanan</i><br/>
		<i>Pilih Tahun untuk Laporan Tahunan</i>
		</div>
  </section>
<!--End Laporan perhari -->
	</div>
</div>
   <?include "footer.phtml"; ?>