<?php
//Format Tanggal Berbahasa Indonesia 

	// Array Hari
	$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
	$hari = $array_hari[date('N')];

	//Format Tanggal 
	$tanggal = date ('j');

	//Array Bulan 
	$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
	$bulan = $array_bulan[date('n')];
	 
	//Format Tahun 
	$tahun = date('Y');

$nama_file= "Laporan Data Keseluruhan_".date('Y').".xls";
?>

<?php
	header("Content-type: application/octet-stream");
	header('Content-Disposition: attachment; filename="' . $nama_file . '"');
	header("Pragma: no-cache");
	header("Expires: 0");
?>




<h3 align ="center">Laporan Data Keseluruhan Surat Pelayanan  <br/>
Tahun <?php echo $this->thn?></h3>

<!-- Start-->
<table style="border-top:3px solid #004D66; border-bottom:3px solid #004D66;" >
  <tr align ="center" style="background-color:#004D66;color: #fff ">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>Jenis Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Pejabat Kelurahan</th>
	  <th>Petugas Proses</th>
	  <th>Petugas Antrian</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->cetak as $data) : ?>
	<tr style="border-bottom:1px solid #F0F0E1; ">
		<td  align="center"><?php echo $i;?></td>		
		<td  align="center"><?php $no_registrasi = substr($this->escape($data->no_registrasi),-4); echo "'".$no_registrasi;?></td>
		<td><?php echo $this->escape($data->jenis_surat);?></td>	
		<td  align="left"><?php echo "'".$this->escape($data->nik);?></td>
		<td  align="left"><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td  align="center"><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td align="center"><?php echo $this->escape($data->kode_pos);?></td>
		<td align="center"><?php echo $this->escape($data->nama_pejabat);?></td>
		<td align="center"><?php echo $this->escape($data->nama_pejabat);?></td>
		<td align="center"><?php echo $this->escape($data->nama_pejabat);?></td>
		
	
	</tr>
	
<?php $i++; endforeach; ?>
	<tr style="background-color:#DBDBEA;color: #000000 ">
		<td colspan='7'><b>Jumlah permintaan surat yang dilayani keseluruhan sebanyak</b></td>
		<td colspan='4'><b><?php echo $i=$i-1 ."  "?> Permintaan Surat</b></td>
	</tr>
</table>