<? include "header.phtml"; ?>
<?php 
	if($this->id_jenis_pengguna == '1'){
		include "menubaradmin.phtml";
	}else{
		include "menubarpemberdayaan.phtml";	
	}
?>
<?// include "barkanan.phtml"; ?>
<div id="contentadmin">

<h1>Cetak Data Layanan Per Petugas Layanan</h1>

<h3 align="center">Silakan pilih petugas</h3>
<p>
<!--Laporan per petugas layanan-->
	<div class="form_settings2" align="center">
		<form action="<? echo $this->basePath;?>/home/index/laporanperpetugas" method="post">
			<select name="petugas">
				<option selected="selected">--Petugas--</option>				
				<?php $i=1; foreach($this->petugas as $data) : ?>
				<option value="<?php echo $this->escape($data->id_pengguna);?>"> <?php echo $this->escape($data->nama_pengguna);?></option>
				<?php $i++; endforeach; ?>
			</select>	
	</p>			
		<p>
			<button class="cetak" align="center">Cetak</button>
		</p>
		</form>			
	</div>



	
	</div>
</div>
<?include "footer.phtml"; ?>