<?php
	header("Content-type: application/octet-stream");
	header("Content-Disposition: attachment; filename = Data Laporan Petugas.xls");
	header("Pragma: no-cache");
	header("Expires: 0");
?>
<h3 align ="center">Laporan Petugas <?php echo $this->nama_petugas?></h3>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>Tanggal Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->cetak as $data) : ?>
	<?php $a = explode(":", $data->waktu_total);  
	$a_hour    = $a[0];
	$a_minutes = $a[1];
	$a_seconds = $a[2];
	
	//mengubah menit jadi detik
	$jadi_detik =  $a_minutes * 60;
	//menjumlahkan hasil menit dan detik
	$jumlah_detik = $jadi_detik + $a_seconds;
	//menjumlahkan semua detik
	$total_detik = $total_detik + $jumlah_detik;
	//rata-rata detik
	$rata = $total_detik / $i;
			
	//konfersi total_detik ke menit detik		 
	$jam = floor($total_detik/3600);
	$sisa = $total_detik% 3600;
	$menit = floor($sisa/60);
	$sisa = $sisa % 60;
	$detik = floor($sisa/1);
	
	//konfersi rata-rata ke menit detik		 
	$jam_rata = floor($rata/3600);
	$sisa = $rata% 3600;
	$menit_rata = floor($sisa/60);
	$sisa = $sisa % 60;
	$detik_rata = floor($sisa/1); ?>
	<tr>
		<td><?php echo $i;?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td>Permintaan Andon Nikah</td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
	</tr>
<?php $i++; endforeach; ?>	
	 <tr>
		<td align="center" colspan="6"><b>Jumlah</b></td>
		<td><b><?php echo $jam." jam ".$menit." menit ".$detik." detik " ?></b></td>
	</tr> 

	<tr>
		<td align="center" colspan="6"><b>Rata-rata</b></td>
		<td><b><?php echo $jam_rata." jam ".$menit_rata." menit ".$detik_rata." detik " ?></b></td>
	</tr>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " . $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
