<? include "header.phtml"; ?>
<?php 
	if($this->id_jenis_pengguna == '1'){
		include "menubaradmin.phtml";
	}else{
		include "menubarpemberdayaan.phtml";	
	}
?>
<? include "jam.php"; ?>
<div class="content">
	<h1>Data Laporan Kinerja Waktu Pelayanan</h1>
	<?php // peringatan/ notifikasi waktu pelayanan
			if($this->peringatan)
			echo $this->peringatan;
	?>
<h3 align="center">Silakan Pilih Nama Surat</h3>
<p>
<div class="form_settings2" align="center">
	<form action="<? echo $this->basePath;?>/home/index/laporanwaktu" method="post">
		<select name="namasurat">
			<option selected="selected">--Nama Surat--</option>				
			<option value="permintaan_andonnikah">Keterangan Andon Nikah</option>				
			<option value="permintaan_bd">Keterangan Bersih Diri</option>				
			<option value="permintaan_belummenikah">Keterangan Belum Menikah</option>				
			<option value="permintaan_bpr">Keterangan Belum Memiliki Rumah</option>				
			<option value="permintaan_domisili_parpol">Keterangan Domisili Parpol</option>				
			<option value="permintaan_domisili_perusahaan">Keterangan Domisili Perusahaan</option>				
			<option value="permintaan_domisili_yayasan">Keterangan Domisili Yayasan</option>				
			<option value="permintaan_ibadahhaji">Keterangan Menunaikan Ibadah Haji</option>				
			<option value="permintaan_ik">Keterangan Ijin Keramaian</option>				
			<option value="permintaan_janda">Keterangan Status Janda</option>				
			<option value="permintaan_keterangan_tempat_usaha">Keterangan Tempat Usaha</option>				
			<option value="permintaan_lahir">Keterangan Kelahiran</option>				
			<option value="permintaan_mati">Keterangan Kematian</option>				
			<option value="permintaan_ps">Keterangan SKCK</option>				
			<option value="permintaan_rumahsakit">Keterangan SKTM Rumah Sakit</option>				
			<option value="permintaan_sekolah">Keterangan SKTM Sekolah</option>				
			<option value="permintaan_waris">Keterangan Waris</option>				
			<option value="permintaan_serbaguna">Surat Serbaguna</option>				
			
		</select>	
</p>			
	<p>
	<button class="cetak" name="pilih" align="center">Pilih</button>
	</p>
	</form>			
	</div>

<?php if(isset($_POST['pilih'])){ ?>
	<?php echo "<h2 align='center'>". $this->judul_surat ."</h2><br />"; ?>
	<!-- <table border="1" style="width:100%; border-spacing:0;" id="rounded-corner">
          <tr align ="center">
			  <th>Tanggal Surat</th>
			  <th>No. Surat</th>
			  <th>Waktu Antrian</th>
			  <th>Waktu Proses</th>
			  <th>Waktu Selesai</th>
			  <th>Total Waktu</th>
			 
		  </tr>-->
		 <?php 
		 $durasi= 0;
		 
		 $i=1; 
		 foreach($this->waktu as $data) : 
		 $a = explode(":", $data->waktu_total);  
		$a_hour    = $a[0];
		$a_minutes = $a[1];
		$a_seconds = $a[2];
		
		//mengubah menit jadi detik
		$jadi_detik =  $a_minutes * 60;
		//menjumlahkan hasil menit dan detik
		$jumlah_detik = $jadi_detik + $a_seconds;
		//menjumlahkan semua detik
		$total_detik = $total_detik + $jumlah_detik;
		//rata-rata detik, total detik : jumlah surat
		$rata = $total_detik / $i;
				
		//konfersi total_detik ke menit detik		 
		$jam = floor($total_detik/3600);
		$sisa = $total_detik% 3600;
		$menit = floor($sisa/60);
		$sisa = $sisa % 60;
		$detik = floor($sisa/1);
		
		//konfersi rata-rata ke menit detik		 
		$jam_rata = floor($rata/3600);
		$sisa = $rata% 3600;
		$menit_rata = floor($sisa/60);
		$sisa = $sisa % 60;
		$detik_rata = floor($sisa/1);
		?>
		 <input type="hidden" name="namasurat" value="<?php echo $this->namasurat?>">
		<tr>
            <td><?php $this->escape($data->tanggal_surat);?></td>
            <td><?php $this->escape($data->no_surat);?></td>
            <td><?php $this->escape($data->waktu_antrian);?></td>
            <td><?php $this->escape($data->waktu_proses);?></td>
            <td><?php $this->escape($data->waktu_selesai);?></td>
            <td><?php $this->escape($data->waktu_total);?></td>
		</tr>
		<?php $i++; endforeach; ?>
		
		<table border="0" style="width:100%; border-spacing:0;" id="rounded-corner">
        <tr>
			<td align="center"><b>Jumlah Layanan</b></td>
			<td><b>:<b></td>
			<td><b><?php echo $i-1 ." surat " ?></b></td>
		</tr> 

		<tr>
			<td align="center"><b>Jumlah Waktu</b></td>
			<td><b>:<b></td>
			<td><b><?php echo $jam." jam ".$menit." menit ".$detik." detik " ?></b></td>
		</tr> 

		<tr>
			<td align="center"><b>Rata-rata</b></td>
			<td><b>:<b></td>
			<td><b><?php echo $jam_rata." jam ".$menit_rata." menit ".$detik_rata." detik " ?></b></td>
		</tr>
		<tr>
			<td align="center"><b>Waktu yang ditetapkan Perwal</b></td>
			<td><b>:<b></td>
			<td><b> <?php echo $perwal = 15 ." menit "; ?>	</b></td>
		</tr>
		<tr>
			<td align="center"><b>Status</b></td>
			<td><b>:<b></td>
			<?php
				if($menit_rata <= $perwal){
					echo "<td style='background-color:#80FF00'> <b>Sesuai dengan waktu yang ditetapkan Perwal</b></td>";
				}else{
					echo "<td style='background-color:#FF0000'> <b>Diatas dari waktu yang ditetapkan Perwal</b> </td>";
				}
			?>
			
		</tr>
    </table>
	<p>
	<a href="<?php echo $this->basePath;?>/home/index/laporanwaktucetak?namasurat=<?php echo $this->namasurat;?>"><button class="cetak" name="cetak" align="center">cetak laporan</button></a>
	</p>
<?php 	
} ?>
		
		
  </div>
 </div>

<?include "footer.phtml"; ?>