<?php
	header("Content-type: application/octet-stream");
	header("Content-Disposition: attachment; filename = Data Laporan Keseluruhan.xls");
	header("Pragma: no-cache");
	header("Expires: 0");
?>
<h3 align ="center">Laporan Data Keseluruhan Surat Pelayanan</h3>

<!-- Start-->
<h4>Laporan Data Andonnikah</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanAndonnikah as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Bersih Diri</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanBd as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Belum Menikah</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanBelummenikah as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Belum Punya Rumah</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanBpr as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Domisili Parpol</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanDomisiliParpol as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Domisili Perusahaan</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanDomisiliPerusahaan as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Domisili Yayasan</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanDomisiliYayasan as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Ibadah Haji</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanIbadahHaji as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Ijin Keramaian</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanIk as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhanJanda</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanJanda as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data Keterangan Tempat Usaha</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanKeteranganTempatUsaha as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Lahir</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanLahir as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Mati</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanMati as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Pengantar SKCK</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanPs as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Rumah Sakit</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanRumahSakit as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Sekolah</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanSekolah as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

<!-- Start-->
<h4>Laporan Data keseluruhan Serbaguna</h4>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
	  <th>Jenis Surat</th>
	  <th>Nama Surat</th>
	  <th>Waktu Antrian</th>
	  <th>Waktu Proses</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>Oleh</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhanSerbaguna as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
		<td><?php echo $this->escape($data->nama_jenis_surat);?></td>
		<td><?php echo $this->escape($data->nama_surat);?></td>
		<td><?php echo $this->escape($data->waktu_antrian);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " .$hari. ", " ." ". $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>
<!-- End-->

