<?php
//Format Tanggal Berbahasa Indonesia 

	// Array Hari
	$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
	$hari = $array_hari[date('N')];

	//Format Tanggal 
	$tanggal = date ('j');

	//Array Bulan 
	$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
	$bulan = $array_bulan[date('n')];
	 
	//Format Tahun 
	$tahun = date('Y');

$nama_file= "Laporan Data Keseluruhan_".date('dmY').".xls";
?>

<?php
	header("Content-type: application/octet-stream");
	header('Content-Disposition: attachment; filename="' . $nama_file . '"');
	header("Pragma: no-cache");
	header("Expires: 0");
?>
<style>
table { 
	margin: 10px 0 30px 0;
	width : 100% !important;
	box-shadow: 0 2px 3px rgba(0, 0, 0, 0.2);
	-webkit-box-shadow: 0 2px 3px rgba(0, 0, 0, 0.2);
	-moz-box-shadow: 0 2px 3px rgba(0, 0, 0, 0.2);
	
}

table tr:hover{ 	
	background: #424251 !important;
}

table tr, table tr td { 	
	padding: 10px 5px;
	text-align: left;
	
}


table tr th{ 
	background: #00698C;
	color: #FFF;
	padding: 12px 4px;
	text-align: center;
}

table tr td { 
	background: #DDDDDD;
	color: #444;  
	border-bottom : 1px solid #CCCCCC;;
}
</style>



<h3 align ="center">Laporan Data Keseluruhan Surat Pelayanan</h3>
<?php echo "<h4  align ='center'> ".$tanggal ." ". $bulan ." ". $tahun."</h4>";?>

<!-- Start-->
<table border="1">
  <tr align ="center" style="background-color:#0086B3;color: #fff ">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>Jenis Surat</th>
	  <th>Tanggal Surat</th>
	  <th>NIK</th>
	  <th>Nama Warga</th>
	  <th>Jenis Kelamin</th>
	  <th>Tempat / Tanggal Lahir</th>
	  <th>Alamat</th>
	  <th>RT / RW</th>
	  <th>Kode Pos</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->keseluruhan as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		<td><?php echo "'".$this->escape($data->nik);?></td>
		<td><?php echo $this->escape($data->nama);?></td>
		<td><?php echo $this->escape($data->jenis_kelamin);?></td>
		<td><?php echo $this->escape($data->tempat_lahir);echo ", ";echo $this->escape($data->tanggal_lahir);?></td>
		<td><?php echo $this->escape($data->alamat);?></td>
		<td><?php echo "'".$this->escape($data->rt);echo "/";echo "'".$this->escape($data->rw);?></td>
		<td><?php echo $this->escape($data->kode_pos);?></td>
	
	</tr>
<?php $i++; endforeach; ?>
</table>



<!-- End-->

