<? include "header.phtml"; ?>
<?php 
	if($this->id_jenis_pengguna == '1'){
		include "menubaradmin.phtml";
	}else{
		include "menubarpemberdayaan.phtml";	
	}
?>
<? include "jam.php"; ?>
<div class="content">
	<h1>Data Laporan Kinerja Waktu Pelayanan</h1>
	<?php // peringatan/ notifikasi waktu pelayanan
			if($this->peringatan)
			echo $this->peringatan;
	?>
<h3 align="center">Silakan Pilih Nama Surat</h3>
<p>
<div class="form_settings2" align="center">
	<form action="<? echo $this->basePath;?>/home/index/laporanwaktu" method="post">
		<select name="namasurat">
			<option selected="selected">--Nama Surat--</option>	
			
			<option value="permintaan_adm_cerai">Ket. Adm. Cerai</option>				
			<option value="permintaan_ajb">Ket. Tanah & Bangunan (AJB)</option>		
			<option value="permintaan_sertifikat">Ket. Tanah & Bangunan (Sertifikat)</option>		
			<option value="permintaan_andonnikah">Ket. Andon Nikah</option>				
			<option value="permintaan_bd">Ket. Bersih Diri</option>				
			<option value="permintaan_belummenikah">Ket. Belum Menikah</option>				
			<option value="permintaan_belum_bekerja">Ket. Belum Bekerja</option>				
			<option value="permintaan_bpr">Ket. Belum Memiliki Rumah</option>				
			<option value="permintaan_domisili_panitia_pembangunan">Ket. Domisili Panitia Pembangunan</option>				
			<option value="permintaan_domisili_parpol">Ket. Domisili Parpol</option>				
			<option value="permintaan_domisili_penduduk">Ket. Domisili Penduduk</option>				
			<option value="permintaan_domisili_perusahaan">Ket. Domisili Perusahaan</option>				
			<option value="permintaan_domisili_yayasan">Ket.Domisili Yayasan</option>				
			<option value="permintaan_ibadahhaji">Ket.Menunaikan Ibadah Haji</option>				
			<option value="permintaan_ik">Ket. Ijin Keramaian</option>	
			<option value="permintaan_imb">Ket. Ijin Mendirikan Bangunan</option>			
			<option value="permintaan_janda">Ket. Status Janda / Duda</option>	
			<option value="permintaan_kartuidentitaskerja">Ket. Kartu Identitas Kerja</option>	
			<option value="permintaan_keterangan_tempat_usaha">Keterangan Tempat Usaha</option>	
			<option value="permintaan_kipem">Ket. Kipem</option>	
			<option value="permintaan_kk">Kartu Keluarga (KK)</option>	
			<option value="permintaan_ktp">Kartu Tanda Penduduk (KTP)</option>				
			<option value="permintaan_lahir">Ket. Kelahiran Lama</option>				
			<option value="permintaan_mati">Ket. Kematian Lama</option>
			<option value="permintaan_lahir_baru">Ket. Kelahiran Baru</option>				
			<option value="permintaan_mati_baru">Ket. Kematian Baru</option>	
			<option value="permintaan_na">Ket. Nikah (NA)</option>
			<option value="permintaan_orang_yang_sama">Ket. Orang yang Sama</option>
			<option value="permintaan_pbb_mutasi">Ket. Mutasi Balik Nama PBB</option>
			<option value="permintaan_pbb_split">Ket. Split PBB Pemecahan</option>
			<option value="permintaan_pbb_penerbitan">Ket. Penerbitan SPPT PBB</option>			
			<option value="permintaan_ps">Pengantar SKCK</option>				
			<option value="permintaan_rumahsakit">Ket.SKTM Rumah Sakit</option>				
			<option value="permintaan_sekolah">Ket. SKTM Sekolah</option>				
			<option value="permintaan_siup">Ket. SIUP</option>
			<option value="permintaan_suratkuasa">Ket. Surat Kuasa</option>			
			<option value="permintaan_waris">Ket. Waris</option>				
			<option value="permintaan_serbaguna">Surat Serbaguna</option>				
			
		</select>	
</p>			
	<p>
	<button class="cetak" name="pilih" align="center">Pilih</button>
	</p>
	</form>			
	</div>

<?php if(isset($_POST['pilih'])){ ?>
	<?php echo "<h2 align='center'>". $this->judul_surat[$this->namasurat] ."</h2><br />"; ?>
	<!-- <table border="1" style="width:100%; border-spacing:0;" id="rounded-corner">
          <tr align ="center">
			  <th>Tanggal Surat</th>
			  <th>No. Surat</th>
			  <th>Waktu Antrian</th>
			  <th>Waktu Proses</th>
			  <th>Waktu Selesai</th>
			  <th>Total Waktu</th>
			 
		  </tr>-->
		 <?php 
		 $durasi= 0;
		 
		$i=1; 
		foreach($this->waktu as $data) : 
		$a = explode(":", $data->waktu_total);  
		$a_hour    = $a[0];
		$a_minutes = $a[1];
		$a_seconds = $a[2];
		
		//mengubah menit jadi detik
		$jadi_detik =  $a_minutes * 60;
		//menjumlahkan hasil menit dan detik
		$jumlah_detik = $jadi_detik + $a_seconds;
		//menjumlahkan semua detik
		$total_detik = $total_detik + $jumlah_detik;
		//rata-rata detik, total detik : jumlah surat
		$rata = $total_detik / $i;
				
		//konfersi total_detik ke menit detik		 
		$jam = floor($total_detik/3600);
		$sisa = $total_detik% 3600;
		$menit = floor($sisa/60);
		$sisa = $sisa % 60;
		$detik = floor($sisa/1);
		
		//konfersi rata-rata ke menit detik		 
		$jam_rata = floor($rata/3600);
		$sisa = $rata% 3600;
		$menit_rata = floor($sisa/60);
		$sisa = $sisa % 60;
		$detik_rata = floor($sisa/1);
		?>
		 <input type="hidden" name="namasurat" value="<?php echo $this->namasurat?>">
		<tr>
            <td><?php $this->escape($data->tanggal_surat);?></td>
            <td><?php $this->escape($data->no_surat);?></td>
            <td><?php $this->escape($data->waktu_antrian);?></td>
            <td><?php $this->escape($data->waktu_proses);?></td>
            <td><?php $this->escape($data->waktu_selesai);?></td>
            <td><?php $this->escape($data->waktu_total);?></td>
		</tr>
		<?php $i++; endforeach; ?>
		
		<table border="0" style="width:100%; border-spacing:0;" id="rounded-corner">
        <tr>
			<td align="center"><b>Jumlah Layanan</b></td>
			<td><b>:<b></td>
			<td><b><?php echo $i-1 ." surat " ?></b></td>
		</tr> 

		<tr>
			<td align="center"><b>Jumlah Waktu</b></td>
			<td><b>:<b></td>
			<td><b><?php echo $jam." jam ".$menit." menit ".$detik." detik " ?></b></td>
		</tr> 

		<tr>
			<td align="center"><b>Rata-rata</b></td>
			<td><b>:<b></td>
			<td><b><?php echo $jam_rata." jam ".$menit_rata." menit ".$detik_rata." detik " ?></b></td>
		</tr>
		<tr>
			<td align="center"><b>Waktu yang ditetapkan Perwal</b></td>
			<td><b>:<b></td>
			<td><b> <?php echo $perwal = 15 ." menit "; ?>	</b></td>
		</tr>
		<tr>
			<td align="center"><b>Status</b></td>
			<td><b>:<b></td>
			<?php
				if($menit_rata <= $perwal){
					echo "<td style='background-color:#80FF00'> <b>Sesuai dengan waktu yang ditetapkan Perwal</b></td>";
				}else{
					echo "<td style='background-color:#FF0000'> <b>Diatas dari waktu yang ditetapkan Perwal</b> </td>";
				}
			?>
			
		</tr>
    </table>
	<p>
	<a href="<?php echo $this->basePath;?>/home/index/laporanwaktucetak?namasurat=<?php echo $this->namasurat;?>"><button class="cetak" name="cetak" align="center">cetak laporan</button></a>
	</p>
<?php 	
} ?>
		
		
  </div>
 </div>

<?include "footer.phtml"; ?>