<?php
	header("Content-type: application/octet-stream");
	header("Content-Disposition: attachment; filename = Data Laporan Keterangan Kematian Lama Per Tahun.xls");
	header("Pragma: no-cache");
	header("Expires: 0");
?>
<h3 align ="center">Laporan Data Keterangan Kematian Lama Per Tahun <?php echo $this->thn?></h3>
<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>No Registrasi</th>
	  <th>No Surat</th>
	  <th>Tanggal Surat</th>
		  
	  <th>Nama Jenazah</th>
	  <th>Tempat / Tanggal Lahir Jenazah</th>
	  <th>Alamat Jenazah</th>
	  <th>Hari / Tanggal Meninggal</th>
	  <th>Tempat Meninggal</th>
	  <th>Sebab Meninggal</th>
	  
	  <th>Waktu Antrian</th>
	  <th>Antrian Oleh</th>
	  <th>Waktu Proses</th>
	  <th>Proses Oleh</th>
	  <th>Waktu Selesai</th>
	  <th>Waktu Total</th>
	  <th>TTD</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->cetak as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->no_registrasi);?></td>
		<td><?php echo $this->escape($data->no_surat);?></td>			
		<td><?php echo $this->escape($data->tanggal_surat);?></td>
		
		<td><?php echo $this->escape($data->nama_meninggal);?></td>
		<td><?php echo $this->escape($data->tempat_lahir_meninggal);echo ", ";echo $this->escape($data->tanggal_lahir_meninggal);?></td>
		<td><?php echo $this->escape($data->alamat_meninggal);?></td>
		<td><?php echo $this->escape($data->hari_meninggal);echo ", ";echo $this->escape($data->tanggal_meninggal);?></td>
		<td><?php echo $this->escape($data->tempat_meninggal);?></td>
		<td><?php echo $this->escape($data->sebab_meninggal);?></td>
		
		<td><?php echo $this->escape($data->waktu_antrian);?></td>		
		<td><?php echo $this->escape($data->nama_pegawai);?></td>
		<td><?php echo $this->escape($data->waktu_proses);?></td>
		<td><?php echo $this->escape($data->nama_pegawai);?></td>
		<td><?php echo $this->escape($data->waktu_selesai);?></td>
		<td><?php echo $this->escape($data->waktu_total);?></td>
		<td><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " . $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>