	
	<nav>
        <ul class="sf-menu" id="nav">
		  <li><a href="">Adm Pengguna</a>
            <ul>
			  <li><a href="<? echo $this->basePath;?>/home/index/tambahpengguna">Tambah Pengguna</a></li>
			  <li><a href="<? echo $this->basePath;?>/home/index/homeadmin">Data Pengguna</a></li>
            </ul>
          </li>
		  <li><a href="">Adm Pejabat Kelurahan</a>
            <ul>
				<li><a href="<? echo $this->basePath;?>/home/index/tambahpejabat">Tambah Pejabat</a></li>
				<li><a href="<? echo $this->basePath;?>/home/index/datapejabat">Data Pejabat</a></li>
            </ul>
          </li>
		  <li><a href="">Adm Pegawai Kelurahan</a>
            <ul>
				<li><a href="<? echo $this->basePath;?>/home/index/pegawaitambah">Tambah Pegawai</a></li>
				<li><a href="<? echo $this->basePath;?>/home/index/pegawaidata">Data Pegawai</a></li>
            </ul>
          </li>
          <li><a href="#">Laporan</a>  
			<ul>
				<li><a href="<? echo $this->basePath;?>/home/index/laporankeseluruhancetak">Data Pelayanan Keseluruhan</a></li>
				<li><a href="#">Data Layanan Per Jenis Layanan</a>
					<ul>
						<li><a href="#">Pemberdayaan</a>
							<ul>							   
								<?php foreach($this->pemberdayaan as $data): ?>
									<li><a href="<? echo $this->basePath;?>/home/index/<?php  echo $this->escape($data->controller).'cetak';?>?id_surat=<?php  echo $this->escape($data->id_surat);  ?>"><?php echo $this->escape($data->nama_surat); ?></a></li>
								<?php endforeach; ?>
							</ul>
						</li>
						<li><a href="#">Trantib</a>
							<ul>
							   <?php foreach($this->tantrib as $data): ?>
									<li><a href="<? echo $this->basePath;?>/home/index/<?php  echo $this->escape($data->controller).'cetak';  ?>?id_surat=<?php  echo $this->escape($data->id_surat);  ?>"><?php echo $this->escape($data->nama_surat); ?></a></li>
							  <?php endforeach; ?>
							</ul>
						</li>
						<li><a href="#">Ekonomi Pembangunan</a>
							<ul>
								<?php foreach($this->ekonomipembangunan as $data): ?>
									<li><a href="<? echo $this->basePath;?>/home/index/<?php  echo $this->escape($data->controller).'cetak';  ?>?id_surat=<?php  echo $this->escape($data->id_surat);  ?>"><?php echo $this->escape($data->nama_surat); ?></a></li>
								<?php endforeach; ?>
							</ul>
						</li>
						<li><a href="#">Pemerintahan</a>
							<ul>
								<?php foreach($this->pemerintahan as $data): ?>
									<li><a href="<? echo $this->basePath;?>/home/index/<?php  echo $this->escape($data->controller).'cetak';  ?>?id_surat=<?php  echo $this->escape($data->id_surat);  ?>"><?php echo $this->escape($data->nama_surat); ?></a></li>
								<?php endforeach; ?>
							</ul>
					  </li>
					</ul>
				</li>
				<li><a href="<? echo $this->basePath;?>/home/index/laporanpetugas">Data Layanan Per Petugas Layanan</a></li>				
			    <li><a href="<? echo $this->basePath;?>/home/index/laporanwaktu">Data Waktu Layanan</a></li>
			    <li><a href="<? echo $this->basePath;?>/home/index/arsipdata">Data Kelola Kearsipan</a></li>
			</ul>
          </li>
         <li><a href="<? echo $this->basePath;?>/home/index/logout">Logout</a></li>
        </ul>
    </nav>
    </header>