
<nav>
	<ul class="sf-menu" id="nav">
		<li class="selected"><a href="<? echo $this->basePath;?>/surat/index/home">Halaman Utama</a></li>
		<li><a href="#">Surat Permintaan</a>
            <ul>
				<li><a href="#">Pemberdayaan</a>
					<ul>
						<?php foreach($this->pemberdayaan as $data): ?>
						<li><a href="<? echo $this->basePath;?>/surat/index/<?php  echo $this->escape($data->controller);  ?>?id_surat=<?php  echo $this->escape($data->id_surat);  ?>"><?php echo $this->escape($data->nama_surat); ?></a></li>
						<?php endforeach; ?>
					</ul>
				</li>
				<li><a href="#">Tantrib</a>
					<ul>
						<?php foreach($this->tantrib as $data): ?>
						<li><a href="<? echo $this->basePath;?>/surat/index/<?php  echo $this->escape($data->controller);  ?>?id_surat=<?php  echo $this->escape($data->id_surat);  ?>"><?php echo $this->escape($data->nama_surat); ?></a></li>
						<?php endforeach; ?>
					</ul>
				</li>
				
				<li><a href="#">Ekonomi Pembangunan</a>
					<ul>
						<?php foreach($this->ekonomipembangunan as $data): ?>
						<li><a href="<? echo $this->basePath;?>/surat/index/<?php  echo $this->escape($data->controller);  ?>?id_surat=<?php  echo $this->escape($data->id_surat);  ?>"><?php echo $this->escape($data->nama_surat); ?></a></li>
						<?php endforeach; ?>
					</ul>
				</li>
				<li><a href="#">Pemerintahan</a>
					<ul>
						<?php foreach($this->pemerintahan as $data): ?>
						<li><a href="<? echo $this->basePath;?>/surat/index/<?php  echo $this->escape($data->controller);  ?>?id_surat=<?php  echo $this->escape($data->id_surat);  ?>"><?php echo $this->escape($data->nama_surat); ?></a></li>
						<?php endforeach; ?>
					</ul>
				</li>
			    <li style="background-color: #FF9326"><a href="<? echo $this->basePath;?>/surat/index/serbaguna">Lain-lain</a></li>
			</ul>
		</li>		  
        
		<li><a href="<? echo $this->basePath;?>/surat/index/penduduk">Penduduk</a></li>
		<li><a href="<? echo $this->basePath;?>/surat/index/pengambilan">Pengambilan</a></li>
        <li><div class="nama"> .: <?php echo $this->pengguna->nama_pengguna ?> :.</div>
			<ul>	
				<li><a href="#" class='info'>Programmer</a></li>
				<li><a href="<? echo $this->basePath;?>/home/index/logout">Logout</a></li>
				</ul>
		</li>
	</ul>
</nav>
</header>




<style>
	.box {
	width: 600px;
	height: 200px;
	background-color: #2c3e50;
	border-radius: 5px;
	position: absolute;
	left: 50%;
	margin-top: -150px;
	margin-left: -300px;
	top: -9999px;
	z-index: 1000;
	box-shadow: 0 1px 1px rgba(0, 0, 0, 0.4) inset, 0 1px 0 rgba(255, 255, 255, 0.2);
	}
	.box .pesan {
	position: absolute;
	top: 30px;
	right: 10px;
	bottom: 10px;
	left: 10px;
	padding: 5px 10px;
	overflow: auto;
	background-color: #1abc9c;
	color: #fff;
	text-align: left;
	line-height: 1.5em;
	font-size: 14px;
	border-radius: 0 0 5px 5px;
	}
	.pesan .ttd:after {
	content: "";
	position: relative;
	float: right;
	}
	.close:after {
	content: url('<? echo $this->basePath;?>/icon/delete4.png');
	position: absolute;
	top: -10px;
	right: -10px;
	background: #ecf0f1;
	border-radius: 100%;
	padding: 10px;
	z-index: 1000;
	cursor: pointer;
	}
	
</style>


<div class='box'>
	<div class='pesan'>
		Selamat datang di Sistem Informasi Manajemen Kinerja Pelayanan Kelurahan
		<br />
		<br />
		
		
		<i>Developed by:<br />
			Riza Fauzi Rahman <br />085721233926 - riza.fauzi.rahman[at]gmail[dot]com  
		<br />Ratih Pujihati <br /> 085720017874 - ratih.pujihati[at]gmail[dot]com </i>
		<span class='ttd'></span>
	</div>
	<div class='close'></div>
</div>



<script type='text/javascript'>
	//<![CDATA[
	$(document).ready(function () {
		//tampilkan kotak dialog saat muncul dengan class info
		$('.info').click(function () {
			$('.box').fadeIn(9000).css({top: '50%',position: 'fixed'})
			// $('body').css({background: '#123',transition: 'all 5s'}) //efect body berubah warna
		});
		//sembunyikan kotak dialog dengan class close
		$('.close').click(function () {
			$('.box').fadeOut().delay(9000);
			// $('body').css({background: '#ecf0f1',transition: 'all 5s'}) //efect body berubah warna
		})
	});
	//]]>
</script>
