	
	<nav>
        <ul class="sf-menu" id="nav">
          <li><a href="#">Surat Keterangan</a>
            <ul>
			
              <li><a href="#">Pemberdayaan</a>
				<ul>
				   <?php foreach($this->pemberdayaan as $data): ?>
					<li><a href="<? echo $this->basePath;?>/home/index/<?php  echo $this->escape($data->controller);  ?>?id_surat=<?php  echo $this->escape($data->id_surat);  ?>"><?php echo $this->escape($data->nama_surat); ?></a></li>
				  <?php endforeach; ?>
                </ul>
				</li>
				 <li><a href="#">Tantrib</a>
					<ul>
					   <?php foreach($this->tantrib as $data): ?>
						<li><a href="<? echo $this->basePath;?>/home/index/<?php  echo $this->escape($data->controller);  ?>?id_surat=<?php  echo $this->escape($data->id_surat);  ?>"><?php echo $this->escape($data->nama_surat); ?></a></li>
					  <?php endforeach; ?>
					</ul>
			  </li>
			  <li><a href="#">Ekonomi Pembangunan</a>
				<ul>
				   <?php foreach($this->ekonomipembangunan as $data): ?>
					<li><a href="<? echo $this->basePath;?>/home/index/<?php  echo $this->escape($data->controller);  ?>?id_surat=<?php  echo $this->escape($data->id_surat);  ?>"><?php echo $this->escape($data->nama_surat); ?></a></li>
				  <?php endforeach; ?>
                </ul>
			  </li>
			   <li><a href="<? echo $this->basePath;?>/home/index/homeketua">Belum ACC</a></li>
              <li><a href="<? echo $this->basePath;?>/home/index/homeketuaacc">Sudah ACC</a></li>
			  
            </ul>
          </li>
         <li><a href="<? echo $this->basePath;?>/home/index/logout">Logout</a></li>
        </ul>
    </nav>
    </header>