	<nav>
        <ul class="sf-menu" id="nav">
          <li><a href="">Adm Pengguna</a>
            <ul>
			  <li><a href="<? echo $this->basePath;?>/home/index/tambahpengguna">Tambah Pengguna</a></li>
			  <li><a href="<? echo $this->basePath;?>/home/index/homeadmin">Data Pengguna</a></li>
            </ul>
          </li>
		  <li><a href="">Adm Pejabat Kelurahan</a>
            <ul>
				<li><a href="<? echo $this->basePath;?>/home/index/tambahpejabat">Tambah Pejabat</a></li>
				<li><a href="<? echo $this->basePath;?>/home/index/datapejabat">Data Pejabat</a></li>
            </ul>
          </li>
		  <li><a href="">Laporan</a>
            <ul>
			  <li><a href="#">Data Pelayanan Keseluruhan</a></li>
			  <li><a href="#">Data Layanan Per Jenis Layanan</a></li>
			  <li><a href="#">Data Layanan Per Petugas Layanan</a></li>
			  <li><a href="#">Data Waktu Layanan</a></li>
			  <li><a href="#">Data Kelola Kearsipan</a></li>
            </ul>
          </li>
          <li><a href="<? echo $this->basePath;?>/home/index/logout">Logout</a></li>
        </ul>
    </nav>
    </header>