<? include "header.phtml"; ?>
<? include "menubaradmin.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div class="content">
        <h1>Data Pegawai Kelurahan</h1>
		<?php // peringatan/ notifikasi
				if($this->peringatan)
				echo $this->peringatan;
		?>
		<table style="width:100%; border-spacing:0;" id="rounded-corner">
          <tr align ="center">
			  <th>NIP Pegawai</th>
			  <th>Nama Pegawai</th>
			  <th>Jabatan</th>
			  <th>Golongan</th>
			  <th>Alamat</th>
			  <th>No. Telp</th>
			  
			  <th colspan=2>Aksi</th>
		  </tr>
		  <?php $i=1; foreach($this->pegawai as $data) : ?>
			<tr>
            <td><?php echo $this->escape($data->nip_pengguna);?></td>
            <td><?php echo $this->escape($data->nama_pengguna);?></td>
            <td><?php echo $this->escape($data->jabatan);?></td>
            <td><?php echo $this->escape($data->golongan);?></td>
            <td><?php echo $this->escape($data->alamat);?></td>
            <td><?php echo $this->escape($data->no_telp);?></td>
           	
            <td><a href="<?php echo $this->basePath; ?>/home/index/pegawaiedit?id_data_pegawai=<?php echo $this->escape($data->id_data_pegawai);?>"><img src="<? echo $this->basePath;?>/images/user_edit.png" alt="" title="edit" border="0" /></a></td>
            <td><a href="<?php echo $this->basePath; ?>/home/index/pegawaihapus?id_data_pegawai=<?php echo $this->escape($data->id_data_pegawai);?>" class="ask" ><img src="<? echo $this->basePath;?>/images/trash.png" alt="" title="hapus" border="0" /></a></td>
		
			
        </tr>
		<?php $i++; endforeach; ?>
          
        </table>
      </div>
	 </div>
	
   <? include "footer.phtml"; ?>