<? include "header.phtml"; ?>
<? include "menubaradmin.phtml"; ?>
<?// include "barkanan.phtml"; ?>
     
	 <div id="contentadmin">
        <h1>Edit Pengguna</h1>
			<form action="<? echo $this->basePath;?>/home/index/simpanpenggunaedit?id_pengguna=<?php echo $this->pengguna->id_pengguna;?>" method="post">
			  <div class="form_settings">
				
				<input type="text" name="id_data_pegawai"  value="<?php echo $this->pengguna->id_data_pegawai; ?>"/>
				<br>Jenis Pengguna :<br>
				<select name="id_jenis_pengguna" >
					<option value="<?php echo $this->pengguna->id_jenis_pengguna; ?>"><?php echo $this->pengguna->nama_jenis_pengguna; ?> </option>
				<?php foreach($this->jenis_pengguna as $data) : ?>
					<option value="<?php echo $this->escape($data->id_jenis_pengguna);?>"><?php echo $this->escape($data->nama_jenis_pengguna);?></option>
				<?php endforeach; ?>
				</select>
				<br><br>Kelurahan : <?php echo $this->pengguna->nama_kelurahan;?><br>
				<input type="text" name="id_kelurahan" value="<?php echo $this->pengguna->id_kelurahan;?>"/>
				<br><br>Nama Pengguna :<br>
				<input type="text" name="nama_pengguna" value="<?php echo $this->pengguna->nama_pengguna;?>" placeholder="masukan nama pengguna"/>
				<br><br>NIP Pengguna :<br>
				<input type="text" name="nip_pengguna" value="<?php echo $this->pengguna->nip_pengguna;?>" placeholder="masukan nip pengguna"/>
				<br><br>Username :<br>
				<input type="text" name="username" value="<?php echo $this->pengguna->username;?>" placeholder="masukan username"/>
				<br><br>Password :<br>
				<input type="text" name="password" value="<?php echo $this->pengguna->password;?>" placeholder="masukan password"/>
				<br><br><p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="name" value="ubah" /></p>
			  </div>
			</form><br><br></center>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>