<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div id="contentadmin">
        <h1>Surat <?php $i=1; foreach($this->surat as $data) : ?><? echo $this->escape($data->nama_surat); endforeach; ?></h1>
		
		<form action="<? echo $this->basePath;?>/home/index/" method="post">
			  
			  Pencarian
				<select>
					<option>No.Surat</option>
				</select>
				<input width="1px" type="text" name="pencarian" value="" placeholder=""/>
				<input class="submit" type="submit" name="name" value="cari" />
			  
		</form><br>
		<button>tambah permintaan</button></center>
		<table style="width:100%; border-spacing:0;">
          <tr align ="center">
			  <th>No</th>
			  <th>No Surat</th>
			  <th>Tgl Surat</th>
			  <th>NIK</th>
			  <th>Nama Warga</th>
			  <th>RT / RW</th>
			  <th>No. KIP</th>
			  <th colspan=3>Aksi</th>
		  </tr>
		 <?php $i=1; foreach($this->permintaan as $data) : ?>
			<tr>
			<td><?php echo $i;?></td>		
            <td><?php echo $this->escape($data->nomor_surat);?></td>
            <td><?php echo $this->escape($data->tgl_surat);?></td>
            <td><?php echo $this->escape($data->nik);?></td>
            <td><?php echo $this->escape($data->nama_lengkap);?></td>
            <td><?php echo $this->escape($data->rt);echo "/";echo $this->escape($data->rw);?></td>
			<td></td>
           
			
			
            <td><a href="<?php echo $this->basePath; ?>/home/index/jenispengguna_edit?id_pengguna=<?php echo $this->escape($data->id_jenis_pengguna);?>"><img src="<? echo $this->basePath;?>/images/user_edit.png" alt="" title="" border="0" /></a></td>
            <td><a href="<?php echo $this->basePath; ?>/home/index/jenispenggunahapus?id_jenis_pengguna=<?php echo $this->escape($data->id_jenis_pengguna);?>" ><img src="<? echo $this->basePath;?>/images/trash.png" alt="" title="" border="0" /></a></td>
			 <td><a href="<?php echo $this->basePath; ?>/home/index/jenispenggunahapus?id_jenis_pengguna=<?php echo $this->escape($data->id_jenis_pengguna);?>" ><img src="<? echo $this->basePath;?>/images/trash.png" alt="" title="" border="0" /></a></td>
		
			
        </tr>
		<?php $i++; endforeach; ?>
          
        </table>
      </div>
	
   <?include "footer.phtml"; ?>