<b>Profile</b>
			<table class="kosong" border="0">
				<tr>
					<td>Kelurahan</td>
					<td>:</td>
					<td><?php echo $this->pengguna->nama_kelurahan?></td>
				</tr>
				<tr>
					<td>Nama </td>
					<td>:</td>
					<td><?php echo $this->pengguna->nama_pengguna?></td>
				</tr>
				<tr>
					<td>NIP </td>
					<td>:</td>
					<td><?php echo $this->pengguna->nip_pengguna?></td>
				</tr>
				<tr>
					<td>Perihal </td>
					<td>:</td>
					<td>Permintaan Surat Yang Belum Acc</td>
				</tr>
				<tr>
					<td>Jenis Surat </td>
					<td>:</td>
					<td><?php echo $this->surat; ?></td>
				</tr>
			</table>