<? include "header.phtml"; ?>
<? include "menubaradmin.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div id="contentadmin">
        <h1>Data Rumah Sakit Cetak</h1>
		
		<form action="<? echo $this->basePath;?>/home/index/tanggalrs" method="post">
		<div class="form_settings2">
				<select name="bln">
				<option selected="selected">Bulan</option>
				<?php
				$bulan_ind=array("Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember");
				$bulan=array("January","Februari","March","April","May","June","July","August","September","October","November","December");
				$jlh_bln=count($bulan_ind);
				for($c=0; $c<$jlh_bln; $c+=1){
					echo"<option value=$bulan[$c]> $bulan_ind[$c] </option>";
				}
				?>
				</select>
				<select name="thn">
				<option selected="selected">Tahun</option>
				<?php
				for($i=date('Y'); $i>=2010; $i-=1){
				echo"<option value=$i> $i </option>";
				}
				?>
				</select>
				<input class="submit" type="submit" name="name" value="cari" />
			 </div>
		</form><br>
      </div>
	 </div>
	
   <?include "footer.phtml"; ?>