<?php
	header("Content-type: application/octet-stream");
	header("Content-Disposition: attachment; filename = Data Laporan Seluruh Petugas Per Hari.xls");
	header("Pragma: no-cache");
	header("Expires: 0");
?>
<h3 align ="center">Laporan Data Seluruh Petugas Per Tanggal <?php echo $this->tanggal?> Bulan <?php echo $this->bln?> Tahun <?php echo $this->thn?></h3>
<table style="border-top:3px solid #004D66; border-bottom:3px solid #004D66;" border="1">
  <tr align ="center" style="background-color:#004D66;color: #fff ">
	  <th>No</th>
	  <th>Petugas</th>
	  <th>Jumlah Surat Layanan</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->cetak as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>				
		<td><?php echo $this->escape($data->nama_pengguna);?></td>
		<td><?php echo $this->escape($data->jumlah_proses);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " . $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>
<table>
	<tr>
		<td colspan="2">a.n Kelurahan Leuwigajah</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_jenis_pengguna);?></td>
	</tr>
	<tr rowspan="3">
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->escape($data->nama_pejabat);?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo "'".$this->escape($data->nip_pejabat);?></td>
	</tr>
	
</table>