<? include "header.phtml"; ?>
<? include "menubaradmin.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div class="content">
        <h1>Edit Surat</h1>
			<form action="<? echo $this->basePath;?>/home/index/simpansuratedit?id_surat=<?php echo $this->surat->id_surat; ?>" method="post">
			  <div class="form_settings">
				</select>
				<br>Nama Surat :<br>
				<input type="text" name="nama_surat" value="<?php echo $this->surat->nama_surat; ?>" />
				<br>Jenis Surat :<br>
				<select name="id_jenis_surat">
					<option value="<?php echo $this->surat->id_jenis_surat; ?>"> <?php echo $this->surat->nama_jenis_surat; ?></option>
					
					<?php foreach($this->jenissurat as $data):?>
					<option value="<?php echo $this->escape($data->id_jenis_surat)?>"><?php echo $this->escape($data->nama_jenis_surat);?></option>
					<?php endforeach;?>
					
				</select>
				<br><br><p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="name" value="ubah" /></p>
				
			  </div>
			</form><br><br></center>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>