<? include "header.phtml"; ?>
<? include "menubaradmin.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div class="content">
        <h1>Tambah Jenis Pengguna</h1>
			<form id="form1" action="<? echo $this->basePath;?>/home/index/simpanjenispengguna" method="post">
			  <div class="form_settings">
				</select>
				<br><br>Nama Jenis Pengguna :<br>
				<input type="text" name="nama_jenis_pengguna" value="" placeholder="masukan nama jenis pengguna" required/>
				<br><br><p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="name" value="selesai" /></p>
			  </div>
			</form><br><br></center>
      </div>
	 </div>
	
   <?include "footer.phtml"; ?>