<? include "header.phtml"; ?>
<? include "menubaradmin.phtml"; ?>
<?// include "barkanan.phtml"; ?>
       <div id="contentadmin">
        <h1>Tambah Pengguna</h1>
			<form id="form1" action="<? echo $this->basePath;?>/home/index/simpanpengguna" method="post">
			  <div class="form_settings">
				
				
				<br>Jenis Pengguna :<br>
				<select name="id_jenis_pengguna" required>
				<?php foreach($this->jenis_pengguna as $data) : ?>
					<option value="<?php echo $this->escape($data->id_jenis_pengguna);?>"><?php echo $this->escape($data->nama_jenis_pengguna);?></option>
				<?php endforeach; ?>
				</select>
				
				<br><br>Kelurahan :<br>
				<select  name="id_kelurahan" >
				<?php foreach($this->kelurahan as $data) : ?>
					<option value="<?php echo $this->escape($data->id_kelurahan);?>"><?php echo $this->escape($data->nama_kelurahan);?></option>
				<?php endforeach; ?>				
				</select>
				
				<br><br>Nama Pengguna :<br>
				<select  name="id_data_pegawai" required>
				<option  selected>--Nama Pengguna--</option>
				<?php foreach($this->pegawai as $data) : ?>
					<option value="<?php echo $this->escape($data->id_data_pegawai);?>"><?php echo $this->escape($data->nama_pengguna);?> | <?php echo $this->escape($data->nip_pengguna);?></option>	
				<?php endforeach; ?>
				</select>
				
				<br><br>Username :<br>
					<input type="text" name="username" value="" placeholder="masukan username" required/>
				<br><br>Password :<br>
					<input type="password" name="password" value="" placeholder="masukan password" required/>
				<br><br><p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="daftar" value="Daftar" /></p>
			  </div>
			</form><br><br></center>
      </div>
	 </div>
	
   <?include "footer.phtml"; ?>