<? include "header.phtml"; ?>
<? include "menubaradmin.phtml"; ?>
<?// include "barkanan.phtml"; ?>
       <div id="contentadmin">
        <h1>Tambah Pengguna</h1>
			<form action="<? echo $this->basePath;?>/home/index/simpanpengguna" method="post">
			  <div class="form_settings">
				
				
				<br>Jenis Pengguna :<br>
				<select name="id_jenis_pengguna" >
				<?php foreach($this->jenis_pengguna as $data) : ?>
					<option value="<?php echo $this->escape($data->id_jenis_pengguna);?>"><?php echo $this->escape($data->nama_jenis_pengguna);?></option>
					
				  
				<?php endforeach; ?>
				</select>
				<br><br>Kelurahan :<br>
				<select  name="id_kelurahan" >
				<?php foreach($this->kelurahan as $data) : ?>
					<option value="<?php echo $this->escape($data->id_kelurahan);?>"><?php echo $this->escape($data->nama_kelurahan);?></option>
					
				  
				<?php endforeach; ?>
				
				</select>
				<br><br>Nama Pengguna :<br>
				<input type="text" name="nama_pengguna" value="" placeholder="masukan nama pengguna"/>
				<br><br>NIP Pengguna :<br>
				<input type="text" name="nip_pengguna" value="" placeholder="masukan nip pengguna"/>
				<br><br>Username :<br>
				<input type="text" name="username" value="" placeholder="masukan username"/>
				<br><br>Password :<br>
				<input type="text" name="password" value="" placeholder="masukan password"/>
				<br><br><p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="name" value="daftar" /></p>
			  </div>
			</form><br><br></center>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>