<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
		<?php
			$i=$this->offset-1;
		?>
		
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		
		<?php //notifikasi berhasil/gagal
				if($this->peringatan)
				echo $this->peringatan;
		?>
		Pencarian
		<form action="<? echo $this->basePath;?>/surat/index/pencarianandonnikah" method="post">
		<div class="form_settings2">
				<select name="id_pencarian">
					<option value="1">No.Surat</option>
					<option value="2">NIK</option>
				</select>
				<input width="1px" type="text" name="pencarian" value="<? echo $this->cari; ?>" placeholder=""/>
				<input class="submit" type="submit" name="name" value="cari" />
			 </div>
		</form><br>
		
		<form action="<? echo $this->basePath;?>/surat/index/caripendudukandonnikah" method="post">
		<div class="form_settings2">
				<button class="button">tambah antrian</button>
			 </div>
		</form><br>
		
		<table style="width:100%; border-spacing:0;">
          <tr align ="center">
			  <th>No</th>
			  <th>No Registrasi</th>
			  <th>Tgl Surat</th>
			  <th>NIK</th>
			  <th>Nama Warga</th>
			  <th>RT / RW</th>
			  <th colspan=3>Aksi</th>
		  </tr>
		 <?php $i=1; foreach($this->permintaan as $data) : ?>
			<tr>
			<td><?php echo $i;?></td>		
            <td><?php echo $this->escape($data->no_registrasi);?></td>
            <td><?php echo $this->escape($data->tanggal_surat);?></td>
            <td><?php echo $this->escape($data->nik);?></td>
            <td><?php echo $this->escape($data->nama);?></td>
            <td><?php echo $this->escape($data->rt);echo "/";echo $this->escape($data->rw);?></td>
           
			
			<?php //jika status = 1 -> munculkan tombol proses
			if ($data->status==1){?>
			 <td><a href="<?php echo $this->basePath; ?>/surat/index/andonnikahproses?id_permintaan_andonnikah=<? echo $data->id_permintaan_andonnikah;?>&nik=<? echo $data->nik;?>&no_registrasi=<? echo $data->no_registrasi;?>"><img src="<? echo $this->basePath;?>/icon/documents5.png" alt="" width="32px" height="32px" title="proses" border="0" /></a></td>
			<?php }elseif($data->status==2){ ?>
				 <td><a href="<?php echo $this->basePath; ?>/surat/index/andonnikahcetak?id_permintaan_andonnikah=<? echo $data->id_permintaan_andonnikah;?>&nik=<? echo $data->nik;?>&no_registrasi=<? echo $data->no_registrasi;?>"><img src="<? echo $this->basePath;?>/icon/microsoft6.png" alt="" width="32px" height="32px" title="cetak" border="0" /></a></td>
			<?php } ?>
            <td><a href="<?php echo $this->basePath; ?>/surat/index/andonnikahedit?id_permintaan_andonnikah=<?php echo $this->escape($data->id_permintaan_andonnikah);?>"><img src="<? echo $this->basePath;?>/icon/edit26.png" alt="" width="32px" height="32px" title="edit" border="0" /></a></td>
            <td><a href="<?php echo $this->basePath; ?>/surat/index/andonnikahhapus?id_permintaan_andonnikah=<?php echo $this->escape($data->id_permintaan_andonnikah);?>" class="ask"><img src="<? echo $this->basePath;?>/icon/garbage4.png" alt="" width="32px" height="32px" title="hapus" border="0" /></a></td>
			
		
			
        </tr>
		<?php $i++; endforeach; ?>
          
        </table>
		
		<?php
		$jumPage = ceil($this->jumData/$this->dataPerPage);

		// menampilkan link previous
		?>
		<div class="pagination">
		<center>
		<?php
		if ($this->noPage > 1) {
		?>
		<a class="page gradient" href="<?php echo $this->basePath;?>/surat/index/andonnikah?page= <?php echo ($this->noPage-1);?>">&lt;&lt; Prev</a>
		<?php
		}

		// memunculkan nomor halaman dan linknya

		 
		for($page = 1; $page <= $jumPage; $page++)
		{
			if ((($page >= $this->noPage - 3) && ($page <= $this->noPage + 3)) || ($page == 1) || ($page == $jumPage))
			{
				if (($showPage == 1) && ($page != 2))  echo "...";

				if (($showPage != ($jumPage - 1)) && ($page == $jumPage))  echo "...";

				if ($page == $this->noPage) echo " <b>".$page."</b> ";

				else{
					?>
					<a class="page gradient" href="<?php echo $this->basePath;?>/surat/index/andonnikah?page=<?php echo $page; ?>"><?php echo $page; ?> </a>
					<?php
				}
				

				$showPage = $page;

			}

		}

		// menampilkan link next
		if ($this->noPage < $jumPage){
		?>
		
		<a class="page gradient" href="<?php echo $this->basePath;?>/surat/index/andonnikah?page=<?php echo ($this->noPage+1);?>">Next &gt;&gt;</a>
		<?php
		}
		?>
		</center>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>