<?php
 
ini_set('display_errors',1);
error_reporting(-1);

// Format Tanggal Berbahasa Indonesia 

// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

// Format Tanggal 
$tanggal = date ('j');

// Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
// Format Tahun 
$tahun = date('Y');

// panggil template yg telah dibuat
$document = file_get_contents('../etc/data/alamat.rtf');
echo $document;
// isi dokumen 

// header
$document = str_replace('#kelurahan#',$this->hasil->nama_kelurahan, $document);
$document = str_replace('#kecamatan',$this->hasil->kecamatan, $document);
$document = str_replace('#alkelurahan#',$this->hasil->alamat_kelurahan, $document);

// isi surat
$document = str_replace('#no_surat#',$this->hasil->no_surat, $document);
$document = str_replace('#kelurahan#',$this->hasil->nama_kelurahan, $document);
$document = str_replace('#kecamatan',$this->hasil->kecamatan, $document);


$document = str_replace('#nik#',$this->hasil->nik, $document);
$document = str_replace('#nama#',$this->hasil->nama, $document);
$document = str_replace('#tempat_lahir#',$this->hasil->tempat_lahir, $document);
$document = str_replace('#tanggal_lahir#',$this->hasil->tanggal_lahir, $document);
$document = str_replace('#jenis_kelamin#',$this->hasil->jenis_kelamin, $document);
$document = str_replace('#pekerjaan#',$this->hasil->pekerjaan, $document);
$document = str_replace('#agama#',$this->hasil->agama, $document);
$document = str_replace('#alamatwarga#',$this->hasil->alamat_warga, $document);
$document = str_replace('#rt#',$this->hasil->rt, $document);
$document = str_replace('#rw#',$this->hasil->rw, $document);
$document = str_replace('#surat_pengantar#',$this->hasil->no_surat_pengantar, $document);
$document = str_replace('#tanggalsuratpengantar#',$this->hasil->tanggal_surat_pengantar, $document);
$document = str_replace('#pasangan',$this->hasil->nama_pasangan, $document);
$document = str_replace('#alpasangan#',$this->hasil->alamat_pasangan, $document);
$document = str_replace('#pejabat#',$this->hasil->nama_pejabat, $document);
$document = str_replace('#nip#',$this->hasil->nip_pejabat, $document);
$document = str_replace('#tanggalsurat#',$hari . ',' .' '. $tanggal .' '. $bulan .' '. $tahun, $document);
 

 // buat nama file
$namafile = 'ANDONNIKAH_'.$this->hasil->nama.'_'.date('Y-m-d').'.doc';

header("Pragma: public"); // required
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Cache-Control: private",false); // required for certain browsers
echo "<meta http-equiv='Content-Type' content='text/html;charset=utf-8' />";
header("Content-Type: application/msword");
header("Content-Disposition: attachment; filename=\"".$namafile."\";" );
header("Content-Transfer-Encoding: binary");
ob_clean();
flush();

echo $document; 



if( ob_get_level() )
	die("You've got buffering issues");

?>
