	<div id="site_content">
     <!-- <ul id="images">
        <li><img src="<? echo $this->basePath;?>/images/1.jpg" width="600" height="300" alt="seascape_one" /></li>
        <li><img src="<? echo $this->basePath;?>/images/2.jpg" width="600" height="300" alt="seascape_two" /></li>
        <li><img src="images/3.jpg" width="600" height="300" alt="seascape_three" /></li>
        <li><img src="images/4.jpg" width="600" height="300" alt="seascape_four" /></li>
        <li><img src="images/5.jpg" width="600" height="300" alt="seascape_five" /></li>
        <li><img src="images/6.jpg" width="600" height="300" alt="seascape_seascape" /></li>
      </ul>
      -->
	  <div id="sidebar_container">
        <div class="sidebar">
		<h4>Profile</h4>
			<table class="kosong">
				<tr>
					<td>Kelurahan</td>
					<td>:</td>
					<td><?php echo $this->pengguna->nama_kelurahan?></td>
				</tr>
				<tr>
					<td>Nama Pengguna</td>
					<td>:</td>
					<td><?php echo $this->pengguna->nama_pengguna?></td>
				</tr>
				<tr>
					<td>NIP Pengguna</td>
					<td>:</td>
					<td><?php echo $this->pengguna->nip_pengguna?></td>
				</tr>
			</table>
          
          <h4>Kontak Pusat</h4>
		  <table class="kosong">
			<tr>
				<td>Telepon</td>
				<td>:</td>
				<td>0857-8221-3794</td>
			</tr>
			<tr>
				<td>E-mail</td>
				<td>:</td>
				<td>m.ade@student.upi.edu</td>
			</tr>
			<tr>
				<td>Twitter</td>
				<td>:</td>
				<td>madelhaq</td>
			</tr>
			<tr>
				<td>Facebook</td>
				<td>:</td>
				<td>madelhaq</td>
			</tr>
		  </table>
         
        </div>
      </div>