<?php
//Format Tanggal Berbahasa Indonesia 

// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');

//panggil template yg telah ya
$document = file_get_contents("../etc/data/belummenikah_template.rtf");
 
// isi dokumen 

//header
$document = str_replace("#kelurahan#",$this->hasil->nama_kelurahan, $document);
$document = str_replace("#kecamatan",$this->hasil->kecamatan, $document);
$document = str_replace("#alkelurahan#",$this->hasil->alamat_kelurahan, $document);

//isi surat
$document = str_replace("#no_surat",$this->hasil->no_surat, $document);
$document = str_replace("#kelurahan#",$this->hasil->nama_kelurahan, $document);
$document = str_replace("#kecamatan",$this->hasil->kecamatan, $document);

$document = str_replace("#nik",$this->hasil->nik, $document);
$document = str_replace("#nama",$this->hasil->nama, $document);
$document = str_replace("#tempat_lahir",$this->hasil->tempat_lahir, $document);
$document = str_replace("#tanggal_lahir",$this->hasil->tanggal_lahir, $document);
$document = str_replace("#jenis_kelamin",$this->hasil->jenis_kelamin, $document);
$document = str_replace("#pekerjaan",$this->hasil->pekerjaan, $document);
$document = str_replace("#agama",$this->hasil->agama, $document);
$document = str_replace("#alamatwarga",$this->hasil->alamat_warga, $document);
$document = str_replace("#rt",$this->hasil->rt, $document);
$document = str_replace("#rw",$this->hasil->rw, $document);
$document = preg_replace("#surat_pengantar#",$this->hasil->no_surat_pengantar, $document);
$document = str_replace("#tanggalsuratpengantar#",$this->hasil->tanggal_surat_pengantar, $document);
$document = str_replace("#keperluan",$this->hasil->keperluan, $document);
$document = str_replace("#pejabat",$this->hasil->nama_pejabat, $document);
$document = str_replace("#nip",$this->hasil->nip_pejabat, $document);
$document = str_replace("#tanggalsurat",$hari . "," ." ". $tanggal ." ". $bulan ." ". $tahun, $document);
 
 
//buat nama file
$namafile = "BELUMMENIKAH_".$this->hasil->nama."_".$this->hasil->nik."_".date('Y-m-d');

header("Content-type: application/vnd.ms-word");
header("Content-disposition: inline; filename=".$namafile.".rtf");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: public");
header("Content-length: ".strlen($document));
echo $document;

?>