<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		<?php
			if($this->hasil){
		?>
		<form action="<? echo $this->basePath;?>/surat/index/simpanprosesdomisiliyayasanedit?id_permintaan_domisili_yayasan=<?php echo $this->hasil->id_permintaan_domisili_yayasan; ?>	" method="post" >
		<input width="1px" type="hidden" name="nik" value="<?php echo $this->hasil->nik; ?>" placeholder="" readonly />
		<div class="form_settings2">
			
			<table>
				
				</tr>
					<td>Nomor Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat" value="<?php echo $this->hasil->no_surat; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Tanggal Surat</td>
					<td>:</td>
					<td><input width="1px" type="date" name="tanggal_surat" value="<?php echo $this->hasil->tanggal_surat; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Nomor Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat_pengantar" value="<?php echo $this->hasil->no_surat_pengantar; ?>" placeholder=""/  onClick="alert('nomer surat tidak boleh sama')">
					&nbsp &nbsp RT / RW &nbsp &nbsp
					<input width="0" type="kecil" name="rt" value="<?php echo $this->hasil->rt; ?>" placeholder=""/> &nbsp /&nbsp
					<input width="1px" type="kecil" name="rw" value="<?php echo $this->hasil->rw; ?>" placeholder=""/>
					</td>
				</tr>
				<tr>
					<td>Tanggal Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="date" name="tanggal_surat_pengantar" value="<?php echo $this->hasil->tanggal_surat_pengantar; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>masa_berlaku</td>
					<td>:</td>
					<td><input width="1px" type="date" name="masa_berlaku" value="<?php echo $this->hasil->masa_berlaku; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Keperluan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="keperluan" value="<?php echo $this->hasil->keperluan; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Nama Yayasan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_yayasan" value="<?php echo $this->hasil->nama_yayasan; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Bergerak Bidang</td>
					<td>:</td>
					<td><input width="1px" type="text" name="bergerak_bidang" value="<?php echo $this->hasil->bergerak_bidang; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Jumlah Anggota</td>
					<td>:</td>
					<td><input width="1px" type="text" name="jumlah_anggota" value="<?php echo $this->hasil->jumlah_anggota; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Jam Kerja</td>
					<td>:</td>
					<td><input width="1px" type="text" name="jam_kerja" value="<?php echo $this->hasil->jam_kerja; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Alamat Usaha</td>
					<td>:</td>
					<td><textarea name="alamat_usaha"><?php echo $this->hasil->alamat_usaha; ?></textarea></td>
				</tr>
				<tr>
					<td>Mengetahui</td>
					<td>:</td>
					<td><select name="id_pejabat">
						<?php foreach($this->pejabat as $data): ?>
						<option value="<?php echo $this->escape($data->id_pejabat); ?>"><?php echo $this->escape($data->nip_pejabat); ?> | <?php echo $this->escape($data->nama_pejabat); ?></option>
						 <?php endforeach; ?>
						</select>
					</td>					
				</tr>	
			</table>
				
				<input class="button" type="submit" name="name" value="ubah" />
			 </div>
		</form>
		<?php
		}else{
			echo "<h4>Penduduk Belum terdaftar</h4>";
		
		?>
			<h7><a href="<? echo $this->basePath;?>/surat/index/tambahpenduduk"> daftarkan</a></h7>
		<?php } ?>
		<br><br><br>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>