<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		<?php
			if($this->hasil){
		?>
		<form id="form1" action="<? echo $this->basePath;?>/surat/index/simpanprosesdomisiliyayasanedit?id_permintaan_domisili_yayasan=<?php echo $this->hasil->id_permintaan_domisili_yayasan; ?>	" method="post" >
		<input width="1px" type="hidden" name="nik" value="<?php echo $this->hasil->nik; ?>" placeholder="" readonly />
		<div class="form_settings2">
			
			<table id="rounded-corner">
				<input width="1px" type="hidden" name="nik" value="<?php echo $this->hasil->nik; ?>" placeholder="" readonly />
				</tr>
					<td>Nomor Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat" value="<?php echo $this->hasil->no_surat; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Tanggal Surat</td>
					<td>:</td>
					<td><input width="1px" type="date" name="tanggal_surat" value="<?php echo $this->hasil->tanggal_surat; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Nomor Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat_pengantar" value="<?php echo $this->hasil->no_surat_pengantar; ?>" placeholder=""/  onClick="alert('nomer surat tidak boleh sama')">
					&nbsp &nbsp RT / RW &nbsp &nbsp
					<input width="0" type="kecil" name="rt" value="<?php echo $this->hasil->rt; ?>" placeholder=""/> &nbsp /&nbsp
					<input width="1px" type="kecil" name="rw" value="<?php echo $this->hasil->rw; ?>" placeholder=""/>
					</td>
				</tr>
				<tr>
					<td>Tanggal Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="date" name="tanggal_surat_pengantar" value="<?php echo $this->hasil->tanggal_surat_pengantar; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Keperluan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="keperluan" value="<?php echo $this->hasil->keperluan; ?>" placeholder=""/></td>
				</tr>
					<tr>
					<td>Nama Yayasan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_yayasan" value="<?php echo $this->hasil->nama_yayasan; ?>" placeholder="" required/></td>
				</tr>
				<tr>
					<td>Alamat Yayasan</td>
					<td>:</td>
					<td><textarea name="alamat_yayasan" required><?php echo $this->hasil->alamat_yayasan; ?></textarea></td>
				</tr>

				<tr>
					<td>No Akta Notaris</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_akta_notaris" value="<?php echo $this->hasil->no_akta_notaris; ?>" placeholder="" required/></td>
				</tr>

				<tr>
					<td>Notaris</td>
					<td>:</td>

					<td><input width="1px" type="text" name="notaris" value="<?php echo $this->hasil->notaris; ?>" placeholder="" required/></td>
				</tr>

				<tr>
					<td>Nama Ketua</td>
					<td>:</td>

					<td><input width="1px" type="text" name="nama_ketua" value="<?php echo $this->hasil->nama_ketua; ?>" placeholder="" required/></td>
				</tr>
				<tr>
					<td>Nama Sekretaris</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_sekretaris" value="<?php echo $this->hasil->nama_sekretaris; ?>" placeholder="" required/></td>
				</tr>
				<tr>
					<td>Nama Bendahara</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_bendahara" value="<?php echo $this->hasil->nama_bendahara; ?>" placeholder="" required/></td>
				</tr>
				<tr>
					<td>Mengetahui</td>
					<td>:</td>
					<td><select name="id_pejabat">
						<?php foreach($this->pejabat as $data): ?>
						<option value="<?php echo $this->escape($data->id_pejabat); ?>"><?php echo $this->escape($data->nip_pejabat); ?> | <?php echo $this->escape($data->nama_pejabat); ?></option>
						 <?php endforeach; ?>
						</select>
					</td>					
				</tr>	
			</table>

				<input class="button" type="submit" name="name" value="Ubah" />
				<input class="reset" type="reset" name="reset" value="Ulangi" />
				<input action="action" class="kembali"  value="Kembali" onclick="history.go(-1);" />
			 </div>
		</form>
		<?php
		}else{
			echo "<h4>Penduduk Belum terdaftar</h4>";
		
		?>
			<h7><a href="<? echo $this->basePath;?>/surat/index/tambahpenduduk"> daftarkan</a></h7>
		<?php } ?>
		<br><br><br>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>