<?php
	
	//Format Tanggal Berbahasa Indonesia 

	// Array Hari
	$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
	$hari = $array_hari[date('N')];

	//Format Tanggal 
	$tanggal = date ('j');

	//Array Bulan 
	$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
	$bulan = $array_bulan[date('n')];
	 
	//Format Tahun 
	$tahun = date('Y');

	 
	// Include the PHPWord.php, all other classes were loaded by an autoloader
	include '../etc/libs/PHPWord.php';

	// Create a new PHPWord Object
	$PHPWord = new PHPWord();
		
		
	$document = $PHPWord->loadTemplate('../etc/data/template/DomisiliYayasanTemplate.docx');
	//header
	$document->setValue('kecamatan', $this->hasil->kecamatan);
	$document->setValue('kelurahan', $this->hasil->kelurahan);
	$document->setValue('alamat_kelurahan', $this->hasil->alamat_kelurahan);
	
	//isi surat
	$no_surat = substr($this->hasil->no_registrasi,-4);
	$document->setValue('noSurat',$no_surat);
	$document->setValue('alamatYayasan', $this->hasil->alamat_yayasan);
	$document->setValue('rt', $this->hasil->rt);
	$document->setValue('rw', $this->hasil->rw);
	$document->setValue('noSuratpengantar', $this->hasil->no_surat_pengantar);
	
	$tanggal_surat_pengantar = date('d-m-Y', strtotime($this->hasil->tanggal_surat_pengantar ));
	$document->setValue('tanggalSuratpengantar', $tanggal_surat_pengantar);
	
	//yang beda2
	$document->setValue('namaYayasan', $this->hasil->nama_yayasan);		
	$document->setValue('notaris', $this->hasil->notaris);		
	$document->setValue('noAktaNotaris', $this->hasil->no_akta_notaris);		
	$document->setValue('namaKetua', $this->hasil->nama_ketua);		
	$document->setValue('namaSekretaris', $this->hasil->nama_sekretaris);		
	$document->setValue('namaBendahara', $this->hasil->nama_bendahara);		
	$document->setValue('keperluan', $this->hasil->keperluan);		
					
	//titimangsa surat
	$document->setValue('titimangsa',$tanggal ." ". $bulan ." ". $tahun);
	$document->setValue('namaPejabat', $this->hasil->nama_pejabat);
	$document->setValue('nipPejabat', $this->hasil->nip_pejabat);
	
	$path='E:\\';
	
	$namafile = "DomisiliYayasan_".$this->hasil->nama_yayasan."_"."_".date('d M Y').".docx";
	// $document->save('E:\\andonnikahTemplate.docx');
	//$document->save('E:\\'.$nama_file);
	
	
	// At least write the document to webspace:
	$objWriter = PHPWord_IOFactory::createWriter($PHPWord, 'Word2007');
	
	// // save as a random file in temp file
	$temp_file = tempnam(sys_get_temp_dir(), 'PHPWord');
	$document->save($temp_file);
	
	// Your browser will name the file "myFile.docx"
	// regardless of what it's named on the server 
	
	header('Content-Disposition: attachment; filename="' . $namafile . '"');
	header('Content-Transfer-Encoding: binary');
	header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
	header('Expires: 0');
	header('Pragma: public');
	flush();
	readfile($temp_file); // or echo file_get_contents($temp_file);
	unlink($temp_file);  // remove temp file

	
	
	exit;


?>
