<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		<?php
			if($this->hasil){
		?>
		<form id="form1" action="<? echo $this->basePath;?>/surat/index/simpanprosesdomisiliperusahaanedit?id_permintaan_domisili_perusahaan=<?php echo $this->hasil->id_permintaan_domisili_perusahaan; ?>	" method="post">
		<div class="form_settings2">
			
			<table id="rounded-corner">
				<tr>
					<td>NIK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nik" value="<?php echo $this->hasil->nik; ?>" placeholder="" readonly/></td>
				</tr>
				<tr>
					<td>Nama</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama" value="<?php echo $this->hasil->nama; ?>" placeholder="" readonly/></td>
				</tr>
				<tr>
					<td>Nomor KK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_kk" value="<?php echo $this->hasil->no_kk; ?>" placeholder="" readonly/></td>
				</tr>
				<tr>
					<td>Alamat</td>
					<td>:</td>
					<td><textarea name="alamat" readonly><?php echo $this->hasil->alamat; ?></textarea></td>
				</tr>
				<tr>
					<td>Tempat/Tanggal Lahir</td>
					<td>:</td>
					<td><input width="1px" type="text" name="tempat_lahir" value="<?php echo $this->hasil->tempat_lahir; ?>" placeholder="" readonly/> &nbsp /&nbsp <input width="1px" type="text" class="tanggal" name="tanggal_lahir" value="<?php echo $this->hasil->tanggal_lahir; ?>" placeholder="" readonly/></td>
				</tr>
				<tr>
					<td>Agama</td>
					<td>:</td>
					<td><input width="1px" type="text" name="agama" value="<?php echo $this->hasil->agama; ?>" placeholder="" readonly/></td>
				</tr>
				<tr>
					<td>Jenis Kelamin</td>
					<td>:</td>
					<td>
						<select name="jenis_kelamin" readonly>
							<option value="<?php echo $this->hasil->jenis_kelamin; ?>"><?php echo $this->hasil->jenis_kelamin; ?></option>
							<option value="Laki-laki">Laki-laki</option>
							<option value="Perempuan">Perempuan</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Kewarganegaraan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="kewarganegaraan" value="<?php echo $this->hasil->kewarganegaraan; ?>" placeholder="" readonly/></td>
				</tr>
				<tr>
					<td>Pekerjaan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="pekerjaan" value="<?php echo $this->hasil->pekerjaan; ?>" placeholder="" readonly/></td>
				</tr>
				<tr>
					<td>Status Perkawinan</td>
					<td>:</td>
					<td>
						<select name="status_perkawinan" readonly>
							<option value="<?php echo $this->hasil->status_perkawinan; ?>"><?php echo $this->hasil->status_perkawinan; ?></option>
							<option value="Menikah">Menikah</option>
							<option value="Tidak Menikah">Tidak Menikah</option>
							<option value="Janda">Janda</option>
							<option value="Duda">Duda</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Jabatan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="jabatan" value="<?php echo $this->hasil->jabatan ?>" placeholder="" required /></td>
				</tr>
				
					<td>Nomor Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat" value="<?php echo $this->hasil->no_surat; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Tanggal Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" class="tanggal" name="tanggal_surat" value="<?php echo $this->hasil->tanggal_surat; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Nomor Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat_pengantar" value="<?php echo $this->hasil->no_surat_pengantar; ?>" placeholder=""/>
					&nbsp &nbsp RT / RW &nbsp &nbsp
					<input width="0" type="kecil" name="rt" value="<?php echo $this->hasil->rt; ?>" placeholder=""/> &nbsp /&nbsp
					<input width="1px" type="kecil" name="rw" value="<?php echo $this->hasil->rw; ?>" placeholder=""/>
					</td>
				</tr>
				
				<tr>
					<td>Keperluan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="keperluan" value="<?php echo $this->hasil->keperluan; ?>" placeholder=""/></td>
				</tr>
				
				<tr>
					<td>Tanggal Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="text" class="tanggal" name="tanggal_surat_pengantar" value="<?php echo $this->hasil->tanggal_surat_pengantar; ?>" placeholder=""/></td>
				</tr>
				<tr>
				<tr>
					<td>Nama Perusahaan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_perusahaan" value="<?php echo $this->hasil->nama_perusahaan; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Akta Pendirian Perusahaan </td>
					<td>:</td>
					<td><input width="1px" type="text" name="akta_pendirian_perusahaan" value="<?php echo $this->hasil->akta_pendirian_perusahaan; ?>" placeholder="" required/></td>
				</tr>
				<tr>
					<td>Bergerak Bidang</td>
					<td>:</td>
					<td><input width="1px" type="text" name="bergerak_bidang" value="<?php echo $this->hasil->bergerak_bidang; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Notaris</td>
					<td>:</td>
					<td><input width="1px" type="text" name="notaris" value="<?php echo $this->hasil->notaris; ?>" placeholder=""/></td>
				</tr>
				
				<tr>
					<td>Jumlah Pegawai</td>
					<td>:</td>
					<td><input width="1px" type="text" name="jumlah_pegawai" value="<?php echo $this->hasil->jumlah_pegawai; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Jam Kerja</td>
					<td>:</td>
					<td><input width="1px" type="text" name="jam_kerja" value="<?php echo $this->hasil->jam_kerja; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Alamat Usaha</td>
					<td>:</td>
					<td><textarea name="alamat_usaha"><?php echo $this->hasil->alamat_usaha; ?></textarea></td>
				</tr>

				<tr>
					<td>No Telp Perusahaan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="telp_kantor" value="<?php echo $this->hasil->telp_kantor; ?>" placeholder="" required/></td>
				</tr>
				
			<tr>
					<td>Mengetahui</td>
					<td>:</td>
					<td><select name="id_pejabat">
						<?php foreach($this->pejabat as $data): ?>
						<option value="<?php echo $this->escape($data->id_pejabat); ?>"><?php echo $this->escape($data->nip_pejabat); ?> | <?php echo $this->escape($data->nama_pejabat); ?></option>
						 <?php endforeach; ?>
						</select>
					</td>					
				</tr>	
			</table>
				
				<input class="button" type="submit" name="name" value="ubah" />
			 </div>
		</form>
		<?php
		}else{
			echo "<h4>Penduduk Belum terdaftar</h4>";
		
		?>
			<h7><a href="<? echo $this->basePath;?>/surat/index/tambahpenduduk"> daftarkan</a></h7>
		<?php } ?>
		<br><br><br>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>