<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<? include "info.phtml"; ?>
<? include "jam.js"; ?>
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		<?php
			$id_permintaan_domisili_panitia_pembangunan = $_GET['id_permintaan_domisili_panitia_pembangunan'];
			if($this->hasil){
		?>		
	
		
		<form id="form1" action="<? echo $this->basePath;?>/surat/index/simpanprosesdomisilipanitiapemb"  method="post">
		<div class="form_settings2">
		<div class="notification">	
		 <p>INFO:</p>
		 
		 <p><strong><?php echo $this->hasil->nama; ?> sudah menunggu selama :
		<div id="refresh"></div>
		  <div id="time">
			<p><?php echo $this->lama?></p>
		  </div>
		</strong> </p>
		<p>Waktu layanan yang ditentukan oleh perwal adalah selama 15 menit</p>		
		</div>
		
			<input width="1px" type="hidden" name="id_permintaan_domisili_panitia_pembangunan" value="<?php echo $id_permintaan_domisili_panitia_pembangunan; ?>" placeholder="" readonly />
			<input width="1px" type="hidden" name="id_jenis_surat" value="<?php echo $this->getSurat->id_jenis_surat; ?>" placeholder="" readonly />
			<input width="1px" type="hidden" name="id_surat" value="<?php echo $this->getSurat->id_surat; ?>" placeholder="" readonly />
			<input width="1px" type="hidden" name="nik" value="<?php echo $this->hasil->nik; ?>" placeholder="" readonly />
			<table id="rounded-corner">
				<tr>
					<td>No Registrasi</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_registrasi" value="<?php echo $this->no_registrasi; ?>" placeholder="" readonly /></td>
				</tr>
				
				<tr>
					<td>Nomor Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat" value="<?php echo $this->getSurat->kode_surat?> / <?php echo $this->no_registrasi?> / <?php echo $this->KodeKelurahan; ?>" placeholder="" required/></td>
				</tr>
				<tr>
					<td>Tanggal Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" class="tanggal" name="tanggal_surat" value="<? echo date('Y-m-d');?>" placeholder="" required/></td>
				</tr>

				<tr>
					<td>Nomor Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat_pengantar" value="<?php echo $this->hasil->no_surat_pengantar; ?>" placeholder=""/>
					&nbsp &nbsp RT / RW &nbsp &nbsp
					<input width="0" type="kecil" name="rt" value="<?php echo $this->hasil->rt; ?>" placeholder="" readonly /> &nbsp /&nbsp
					<input width="1px" type="kecil" name="rw" value="<?php echo $this->hasil->rw; ?>" placeholder="" readonly />
					</td>
				</tr>
				<tr>
					<td>Tanggal Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="date" name="tanggal_surat_pengantar" value="<?php echo $this->hasil->tanggal_surat_pengantar; ?>" placeholder=""/></td>
				</tr>

				<tr>
					<td>Nama Pembangunan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_pembangunan" value="" placeholder="" required /></td>
				</tr>
				<tr>
					<td>Alamat Domisili Pembangunan</td>
					<td>:</td>
					<td><textarea name="alamat_pembangunan" required ></textarea></td>
				</tr>
				
				<tr>
					<td>Nama Ketua</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_ketua" value="<?php echo $this->hasil->nama; ?>" placeholder="" required /></td>
				</tr>
				
				<tr>
					<td>Nama Sekretaris</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_sekretaris" value="<?php echo $this->hasil->nama_sekretaris; ?>" placeholder="" required /></td>
				</tr>
				
				<tr>
					<td>Nama Bendahara</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_bendahara" value="<?php echo $this->hasil->nama_bendahara; ?>" placeholder="" required /></td>
				</tr>
				
				<tr>
					<td>Keperluan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="keperluan" value="" placeholder="keperluan"/></td>
				</tr>
				
				<tr>
					<td>Mengetahui</td>
					<td>:</td>
					<td><select name="id_pejabat">
						<?php foreach($this->pejabat as $data): ?>
						<option value="<?php echo $this->escape($data->id_pejabat); ?>"><?php echo $this->escape($data->nip_pejabat); ?> | <?php echo $this->escape($data->nama_pejabat); ?></option>
						 <?php endforeach; ?>
						</select>
					</td>					
				</tr>
				
			</table>
				<input class="button" type="submit" name="name" value="Proses" />
				<input class="reset" type="reset" name="reset" value="Ulangi" />
				<input action="action" class="kembali"  value="Kembali" onclick="history.go(-1);" />
			 </div>
		</form>
		<?php
		}else{
			echo "<h4>Penduduk Belum terdaftar</h4>";
		
		?>
			<h7><a href="<? echo $this->basePath;?>/surat/index/tambahpenduduk"> daftarkan</a></h7>
		<?php } ?>
		<br><br><br>
      </div>
	 </div>
	 


  
   <?include "footer.phtml"; ?>
<script type="text/javascript">
   (function() {
    $('form > input').keyup(function() {

        var empty = false;
        $('form > input').each(function() {
            if ($(this).val() == '') {
                empty = true;
            }
        });

        if (empty) {
            $('#tombol').attr('disabled', 'disabled');
        } else {
            $('#tombol').removeAttr('disabled');
        }
    });
})()
</script>

<script>
	$(document).ready(function() { 
		$( "#tanggal" ).datepicker({
		  changeMonth: true,
		  dateFormat: 'yy-mm-dd'
		});
});

</script>