<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		<?php
			if($this->hasil){
		?>
		<form action="<? echo $this->basePath;?>/surat/index/simpanpermintaandomisiliparpoledit?id_permintaan_domisili_parpol=<?php echo $this->hasil->id_permintaan_domisili_parpol; ?>	" method="post">
		<div class="form_settings2">
			
			<table>
				<tr>
					<td>NIK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nik" value="<?php echo $this->hasil->nik; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Nama</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama" value="<?php echo $this->hasil->nama; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Nomor KK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_kk" value="<?php echo $this->hasil->no_kk; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Alamat</td>
					<td>:</td>
					<td><textarea name="alamat"><?php echo $this->hasil->alamat; ?></textarea></td>
				</tr>
				<tr>
					<td>Tempat/Tanggal Lahir</td>
					<td>:</td>
					<td><input width="1px" type="text" name="tempat_lahir" value="<?php echo $this->hasil->tempat_lahir; ?>" placeholder=""/> &nbsp /&nbsp <input width="1px" type="date" name="tanggal_lahir" value="<?php echo $this->hasil->tanggal_lahir; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Agama</td>
					<td>:</td>
					<td><input width="1px" type="text" name="agama" value="<?php echo $this->hasil->agama; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Jenis Kelamin</td>
					<td>:</td>
					<td>
						<select name="jenis_kelamin">
							<option value="<?php echo $this->hasil->jenis_kelamin; ?>"><?php echo $this->hasil->jenis_kelamin; ?></option>
							<option value="Laki-laki">Laki-laki</option>
							<option value="Perempuan">Perempuan</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Kewarganegaraan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="kewarganegaraan" value="<?php echo $this->hasil->kewarganegaraan; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Pekerjaan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="pekerjaan" value="<?php echo $this->hasil->pekerjaan; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Status</td>
					<td>:</td>
					<td>
						<select name="status_perkawinan">
							<option value="<?php echo $this->hasil->status_perkawinan; ?>"><?php echo $this->hasil->status_perkawinan; ?></option>
							<option value="Menikah">Menikah</option>
							<option value="Tidak Menikah">Tidak Menikah</option>
							<option value="Janda">Janda</option>
							<option value="Duda">Duda</option>
						</select>
					</td>
				</tr>
					<td>Nomor Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat" value="<?php echo $this->hasil->no_surat; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Tanggal Surat</td>
					<td>:</td>
					<td><input width="1px" type="date" name="tanggal_surat" value="<?php echo $this->hasil->tanggal_surat; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Nomor Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat_pengantar" value="<?php echo $this->hasil->no_surat_pengantar; ?>" placeholder=""/>
					&nbsp &nbsp RT / RW &nbsp &nbsp
					<input width="0" type="text" name="rt" value="<?php echo $this->hasil->rt; ?>" placeholder=""/> &nbsp /&nbsp
					<input width="1px" type="text" name="rw" value="<?php echo $this->hasil->rw; ?>" placeholder=""/>
					</td>
				</tr>
				<tr>
					<td>Tanggal Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="date" name="tanggal_surat_pengantar" value="<?php echo $this->hasil->tanggal_surat_pengantar; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>masa_berlaku</td>
					<td>:</td>
					<td><input width="1px" type="date" name="masa_berlaku" value="<?php echo $this->hasil->masa_berlaku; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Keperluan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="keperluan" value="<?php echo $this->hasil->keperluan; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Nama Parpol</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_parpol" value="<?php echo $this->hasil->nama_parpol; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Bergerak Bidang</td>
					<td>:</td>
					<td><input width="1px" type="text" name="bergerak_bidang" value="<?php echo $this->hasil->bergerak_bidang; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Jumlah Anggota</td>
					<td>:</td>
					<td><input width="1px" type="text" name="jumlah_anggota" value="<?php echo $this->hasil->jumlah_anggota; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Jam Kerja</td>
					<td>:</td>
					<td><input width="1px" type="text" name="jam_kerja" value="<?php echo $this->hasil->jam_kerja; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Alamat Parpol</td>
					<td>:</td>
					<td><textarea name="alamat_parpol"><?php echo $this->hasil->alamat_parpol; ?></textarea></td>
				</tr>
				<tr>
					<td>NIP Pejabat Kelurahan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nip_pejabat" value="<?php echo $this->hasil->nip_pejabat; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Nama Pejabat Kelurahan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_pejabat" value="<?php echo $this->hasil->nama_pejabat; ?>" placeholder=""/></td>
				</tr>
			</table>
				
				<input class="button" type="submit" name="name" value="ubah" />
			 </div>
		</form>
		<?php
		}else{
			echo "<h4>Penduduk Belum terdaftar</h4>";
		
		?>
			<h7><a href="<? echo $this->basePath;?>/surat/index/tambahpenduduk"> daftarkan</a></h7>
		<?php } ?>
		<br><br><br>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>