<?php
	
	//Format Tanggal Berbahasa Indonesia 

	// Array Hari
	$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
	$hari = $array_hari[date('N')];

	//Format Tanggal 
	$tanggal = date ('j');

	//Array Bulan 
	$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
	$bulan = $array_bulan[date('n')];
	 
	//Format Tahun 
	$tahun = date('Y');

	 
	// Include the PHPWord.php, all other classes were loaded by an autoloader
	include '../etc/libs/PHPWord.php';

	// Create a new PHPWord Object
	$PHPWord = new PHPWord();
		
		
	$document = $PHPWord->loadTemplate('../etc/data/template/DomisiliPanitiaProposalPembangunanTemplate.docx');
	//header
	$document->setValue('kecamatan', $this->hasil->kecamatan);
	$document->setValue('kelurahan', $this->hasil->kelurahan);
	$document->setValue('alamat_kelurahan', $this->hasil->alamat_kelurahan);
	
	//isi surat
	$document->setValue('noSurat', $this->hasil->no_surat);
	
	//yang beda2
	$document->setValue('namaPembangunan', $this->hasil->nama_pembangunan);
	$document->setValue('alamatPembangunan', $this->hasil->alamat_pembangunan);
	$document->setValue('ketua', $this->hasil->nama_ketua);
	$document->setValue('sekretaris', $this->hasil->nama_sekretaris);
	$document->setValue('bendahara', $this->hasil->nama_bendahara);
	$document->setValue('keperluan', $this->hasil->keperluan);
				
	//titimangsa surat
	$document->setValue('titimangsa',$tanggal ." ". $bulan ." ". $tahun);
	$document->setValue('namaPejabat', $this->hasil->nama_pejabat);
	$document->setValue('nipPejabat', $this->hasil->nip_pejabat);
	
	$path='E:\\';
	
	$namafile = "DomisiliPanitiaProposalPembangunanTemplate_".$this->hasil->nama."_"."_".date('Y-m-d').".docx";
	// $document->save('E:\\andonnikahTemplate.docx');
	//$document->save('E:\\'.$nama_file);
	
	
	// At least write the document to webspace:
	$objWriter = PHPWord_IOFactory::createWriter($PHPWord, 'Word2007');
	
	// // save as a random file in temp file
	$temp_file = tempnam(sys_get_temp_dir(), 'PHPWord');
	$document->save($temp_file);
	
	// Your browser will name the file "myFile.docx"
	// regardless of what it's named on the server 
	
	header('Content-Disposition: attachment; filename="' .rawurlencode($namafile) . '"');
	header('Content-Transfer-Encoding: binary');
	header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
	header('Expires: 0');
	header('Pragma: public');
	flush();
	readfile($temp_file); // or echo file_get_contents($temp_file);
	unlink($temp_file);  // remove temp file

	
	
	exit;


?>
