 <div class="footer">
      <p>Sistem Informasi Manajemen Kinerja Kelurahan Pemerintah Kota Cimahi <?php echo date('Y')?></p>
   </div>
  </div>
</body>
</html>

<script type="text/javascript">
    function show_popup()
    {
      document.getElementById('popup').style.display = 'block';  
      document.getElementById('modal-1').style.display = 'visible';  
    }

    window.onload = show_popup;
	
	//efek untuk menghilangkan modal
	$( "#hider" ).click(function() {	
	  $( "#popup" ).hide( "slow" );
	});
	
	//efek untuk menghilangkan notifikasi
	// $( ".notification" ).click(function() {	
	  // $( ".notification" ).slideToggle( "slow" );
	// });
	
	
	//efek untuk menghilangkan notifikasi
	 $(document).ready( function() {
        $('.sukses').delay(3000).fadeOut();
      });
	
	//efek untuk menghilangkan notifikasi
	 $(document).ready( function() {
        $('.gagal').delay(3000).fadeOut();
      });
	
		
</script>

