<div class="footer">
      <p>Sistem Informasi Manajemen Kinerja Pelayanan Kelurahan <br />© Pemerintah Kota Cimahi <?php echo date('Y')?> <br/> <small style="font-size:14px;font-style:italic">Developed by Riza Fauzi Rahman dan Ratih Pujihati</small></p>
   </div>
  </div>
</body>
</html>

<script type="text/javascript">
    function show_popup()
    {
      document.getElementById('popup').style.display = 'block';  
      document.getElementById('modal-1').style.display = 'visible';  
    }

    window.onload = show_popup;
	
	//efek untuk menghilangkan modal
	$( "#hider" ).click(function() {	
	  $( "#popup" ).hide( "slow" );
	});
	
	//efek untuk menghilangkan notifikasi
	// $( ".notification" ).click(function() {	
	  // $( ".notification" ).slideToggle( "slow" );
	// });
	
	
	//efek untuk menghilangkan notifikasi
	 $(document).ready( function() {
        $('.sukses').delay(3000).slideToggle();
      });
	
	//efek untuk menghilangkan notifikasi
	 $(document).ready( function() {
        $('.gagal').delay(3000).slideToggle();
      });
	
	
		
</script>
