<!DOCTYPE HTML>
<html>

<head>
  <title>SIM Kelurahan</title>
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <link rel="icon" href="<? echo $this->basePath;?>/login/logo/cimahi.png" type="image/png">
  <link rel="stylesheet" type="text/css" href="<? echo $this->basePath;?>/css/style.css" />
  <link rel="stylesheet" type="text/css" href="<? echo $this->basePath;?>/css/pagination.css" />
  
  <!-- Modal Effect -->
  <link rel="stylesheet" type="text/css" href="<? echo $this->basePath;?>/ModalWindowEffects/css/component.css" />  
  <!-- End Modal Effect -->
  
  <script type="text/javascript" src="<? echo $this->basePath;?>/js/jquery-1.8.0.min.js"></script>
  <!-- modernizr enables HTML5 elements and feature detects -->
  <script type="text/javascript" src="<? echo $this->basePath;?>/js/modernizr-1.5.min.js"></script>
</head>
<!-- javascript at the bottom for fast page loading -->
<script type="text/javascript" src="<? echo $this->basePath;?>/jquery.min.js"></script>
<script type="text/javascript" src="<? echo $this->basePath;?>/ddaccordion.js"></script>

<script type="text/javascript" src="<? echo $this->basePath;?>/js/jquery.js"></script>
<script type="text/javascript" src="<? echo $this->basePath;?>/js/jquery.validate.js"></script>
<script type="text/javascript" src="<? echo $this->basePath;?>/js/messages_id.js"></script>

<script type="text/javascript" src="<? echo $this->basePath;?>/datepicker/jquery.ui.core"></script>
<script type="text/javascript" src="<? echo $this->basePath;?>/datepicker/jquery.ui.datepicker"></script>
<script type="text/javascript" src="<? echo $this->basePath;?>/datepicker/jquery.ui.widget.js"></script>
  <link rel="stylesheet" type="text/css" href="<? echo $this->basePath;?>/datepicker/demos.css" />
  
<script type="text/javascript" src="<? echo $this->basePath;?>/js/jquery.easing-sooper.js"></script>
<script type="text/javascript" src="<? echo $this->basePath;?>/js/jquery.sooperfish.js"></script>
<script type="text/javascript" src="<? echo $this->basePath;?>/js/jquery.kwicks-1.5.1.js"></script>
<script src="<? echo $this->basePath;?>/jquery.jclock-1.2.0.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('#images').kwicks({
	max : 600,
	spacing : 2
  });
  $('ul.sf-menu').sooperfish();
});
</script>

<!-- javascript untuk validasi dengan mengacu ke id form1 pada form-->
<script>
	$(document).ready(function() {
	$("#form1").validate();
});
</script>

<script src="<? echo $this->basePath;?>/jquery.jclock-1.2.0.js" type="text/javascript"></script>
<script type="text/javascript" src="<? echo $this->basePath;?>/jconfirmaction.jquery.js"></script>

<script type="text/javascript">
	
	$(document).ready(function() {
		$('.ask').jConfirmAction();
	});
	
</script>
<script type="text/javascript">
$(function($) {
    $('.jclock').jclock();
});
</script>

<body>
  <div id="main">
    <header>
      <div id="logo">
        <div id="logo_text">
          <img src="<? echo $this->basePath;?>/images/logosimkel.png" alt="" title="" class="sidebar_icon_right" />
				<div class="jclock"></div	>
	   </div>
		
      </div>
	   
    
  