<? include "header.phtml"; ?>
<? require_once "menubar.phtml"; ?>
      <div class="content">
		
        <h1>Selamat Datang di Sistem Manajemen Kelurahan</h1>
        
		<?php if($this->peringatan)
				echo $this->peringatan;
		?>
			<div class="card">
				<div class="judul">Profil Pengguna</div>			
				<div class="isi ">					
					<p>Nama: <b> <?php echo $this->pengguna->nama_pengguna ?></b></p>
						<p>Kelurahan:</strong> <b><?php echo $this->pengguna->nama_kelurahan ?></b></p>
						<p>Nip: <b><?php echo $this->pengguna->nip_pengguna ?></b></p>
						<p>Jabatan:<b> <?php echo $this->pengguna->jabatan ?></b></p>
						<p>Alamat: <b><?php echo $this->pengguna->alamat ?></b></p>
						<p>Nomor Telp :<b> <?php echo $this->pengguna->no_telp ?></b></p>
				</div>				
			</div>		
		
		
		<h4>Kontak Pusat</h4>
		  <table class="kosong">
			<tr>
				<td>Telepon</td>
				<td>:</td>
				<td>0857-8221-3794</td>
			</tr>
			<tr>
				<td>E-mail</td>
				<td>:</td>
				<td>ratihpujihati@student.upi.edu</td>
			</tr>
			<tr>
				<td>Twitter</td>
				<td>:</td>
				<td>Ratih</td>
			</tr>
			<tr>
				<td>Facebook</td>
				<td>:</td>
				<td>Ratih</td>
			</tr>
		  </table>
      </div>
	 </div>
   <? include "footer.phtml"; ?>
