<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		<?php
			if($this->hasil){
		?>
		<div class="form_settings2">
		<form action="<? echo $this->basePath;?>/surat/index/simpanikantrian" method="post">
			<table id="rounded-corner">		
				<tr>
					<td>No. Registrasi</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_registrasi" value="<?php echo $this->no_registrasi; ?>" readonly/></td>
				</tr>
				<tr>
					<td>NIK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nik"  value="<?php echo $this->hasil->nik; ?>"/></td>
				</tr>
				<tr>
					<td>Nama</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama"  value="<?php echo $this->hasil->nama; ?>"/></td>
				</tr>
				<tr>
					<td>Nomor KK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_kk"  value="<?php echo $this->hasil->no_kk; ?>" /></td>
				</tr>
				<tr>
					<td>Alamat</td>
					<td>:</td>
					<td><textarea name="alamat"><?php echo $this->hasil->alamat; ?></textarea></td>
				</tr>
				<tr>
					<td>RT / RW</td>
					<td>:</td>
					<td><input type="kecil" name="rt" class="kecil" value="<?php echo $this->hasil->rt; ?>"> / <input type="kecil" name="rw" class="kecil" value="<?php echo $this->hasil->rw; ?>"></td>
				</tr>	
				<tr>
					<td>No Telp</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_telp"  value="" /></td>
				</tr>
				<input class="button" type="submit" name="name" value="simpan antrian" />
			</form>
			</div>
		<?php
		}else{
			echo "<h4>Penduduk Belum terdaftar</h4>";
		
		?>
			<h7><a href="<? echo $this->basePath;?>/surat/index/tambahpenduduk"> daftarkan</a></h7>
		<?php } ?>
		<br><br><br>
      </div>
