		<div id="popup">
				<div class="md-content">
					<h3>Hallo</h3>
					<div>
						<p>Anda sedang login dengan menggunakan akun:</p>
						<ul>
							<li><strong>Nama:</strong> <?php echo $this->pengguna->nama_pengguna ?>.</li>
							<li><strong>Nip:</strong> <?php echo $this->pengguna->nip_pengguna ?>.</li>
							<li>Apakah benar Anda pemilik akun tersebut?</li>
						</ul>
						<button class="modal" id="hider">Ya</button>
							<br/> 
						<a href="<? echo $this->basePath;?>/home/index/logout"><button  class="modal">Tidak</button></a>
							
					</div>				
				</div>
			<div class="md-overlay"></div><!-- the overlay element -->
		</div>

	