<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<? include "info.phtml"; ?>
<? include "jam.js"; ?>

      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		<?php
			$id_permintaan_ajb = $_GET['id_permintaan_ajb'];
			if($this->hasil){
		?>
		<form id="form1" action="<? echo $this->basePath;?>/surat/index/simpanprosesktbajb" method="post">
		<div class="form_settings2">
			
		<div class="notification">	
			 <p>INFO:</p>
			 <p><strong><?php echo $this->hasil->nama; ?> sudah menunggu selama :
			 <div id="refresh"></div>
				<div id="time">
					<p><?php echo $this->lama?></p>
				</div> 
			 </strong> </p>
			<p>Waktu layanan yang ditentukan oleh perwal adalah selama 15 menit</p>		
		</div>
		
			<input width="1px" type="hidden" name="id_permintaan_ajb" value="<?php echo $id_permintaan_ajb; ?>" placeholder="" readonly />
			<input width="1px" type="hidden" name="id_jenis_surat" value="<?php echo $this->getSurat->id_jenis_surat; ?>" placeholder="" readonly />
			<input width="1px" type="hidden" name="id_surat" value="<?php echo $this->getSurat->id_surat; ?>" placeholder="" readonly />
			<table id="rounded-corner">
				<tr>
					<td>No Registrasi</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_registrasi" value="<?php echo $this->no_registrasi; ?>" placeholder="" readonly /></td>
				</tr>
				
					<tr>
					<td>Nomor Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat" value="<?php echo $this->getSurat->kode_surat?> / <?php echo $this->no_registrasi?> / <?php echo $this->KodeKelurahan; ?>" placeholder="" required/></td>
				</tr>
				<tr>
				
				<tr>
					<td>Tanggal Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" class="tanggal" name="tanggal_surat" value="<? echo date('Y-m-d');?>" placeholder="" required/></td>
				</tr>
				<tr>
					<td>Nomor Surat Pengantar*<br/> wajib diisi</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat_pengantar" value="" placeholder="" class="required remote" minlength="4"/>
					&nbsp &nbsp RT / RW &nbsp &nbsp
					<input width="0" type="kecil" class="kecil" name="rt" value="<?php echo $this->hasil->rt; ?>" placeholder="" readonly /> &nbsp /&nbsp
					<input width="1px" type="kecil" class="kecil"  name="rw" value="<?php echo $this->hasil->rw; ?>" placeholder="" readonly />
					</td>
				</tr>
				<tr>
					<td>Tanggal Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="text" name="tanggal_surat_pengantar" class="tanggal" value="" placeholder="" required/></td>
				</tr>
				<tr>

				<tr>
					<td colspan="3">Detail Tanah dan Bangunan</td>
					
				</tr>

				<tr>
					<td>NIK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nik" value="<?php echo $this->hasil->nik; ?>" placeholder="" readonly /></td>
				</tr>
				<tr>
					<td>Nama Pemilik</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_pemilik" value="<?php echo $this->hasil->nama; ?>" placeholder="" required /></td>
				</tr>				
				<tr>
					<td>Alamat Pemilik</td>
					<td>:</td>
					<td><textarea name="alamat_pemilik" required ><?php echo $this->hasil->alamat; ?></textarea></td>
				</tr>				
				
				<tr>
					<td>Pekerjaan Pemilik</td>
					<td>:</td>
					<td><input width="1px" type="text" name="pekerjaan_pemilik" value="<?php echo $this->hasil->pekerjaan; ?>" placeholder="pekerjaan"  /></td>
				</tr>
				<tr>
					<td>Luas tanah</td>
					<td>:</td>
					<td><input width="1px" type="text" name="luas_tanah" value="0" placeholder="luas tanah" required digits="true"/> M<sup>2</sup></td>
				</tr>
				<tr>
					<td>Luas Bangunan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="luas_bangunan" value="0" placeholder="luas bangunan" required  digits="true" /> M<sup>2</sup></td>
				</tr>
				<tr>
					<td>Nomor Persil</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_persil" value="" placeholder="nomor persil" required /></td>
				</tr>
				<tr>
					<td>Nomor Kohir</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_kohir" value="" placeholder="nomor kohir" required  /></td>
				</tr>				
				<tr>
					<td colspan="3">Alamat Tanah</td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Blok </td>
					<td>:</td>
					<td><input width="1px" type="text" name="blok_tanah" value="" placeholder="blok tanah"  required/></td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;RT / RW</td>
					<td>:</td>
					<td><input width="1px" type="kecil" name="rt_tanah" value="" placeholder="RT" required /> <input width="1px" type="kecil" name="rw_tanah" value="" placeholder="RW" required /></td>
				</tr>
				
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kelurahan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="kel_tanah" value="" placeholder="kelurahan"  /></td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kecamatan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="kec_tanah" value="" placeholder="kecamatan"  /></td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nomor Akta</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_akta" value="" placeholder="nomor akta tanah"  /></td>
				</tr>
				
				<tr>
					<td colspan="3">Batas</td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Utara</td>
					<td>:</td>
					<td><input width="1px" type="text" name="batas_utara" value="" placeholder="batas utara" required /> </td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Barat</td>
					<td>:</td>
					<td><input width="1px" type="text" name="batas_barat" value="" placeholder="batas barat" required /> </td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Selatan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="batas_selatan" value="" placeholder="batas selatan" required /> </td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Timur</td>
					<td>:</td>
					<td><input width="1px" type="text" name="batas_timur" value="" placeholder="batas timur" required /> </td>
				</tr>
				
				<tr>
					<td>Nomor PBB</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_pbb" value="" placeholder="nomor pbb" required /> </td>
				</tr>
				<tr>
					<td>Harga Tanah per M<sup>2</sup></td>
					<td>:</td>
					<td><input width="1px" type="text" name="harga_tanah" value="0" placeholder="harga tanah" required digits="true" /> </td>
				</tr>
				<tr>
					<td>Harga Bangunan M<sup>2</sup></td>
					<td>:</td>
					<td><input width="1px" type="text" name="harga_bangunan" value="0" placeholder="harga bangunan" required  digits="true"/> </td>
				</tr>



				<tr>
					<td>Mengetahui</td>
					<td>:</td>
					<td><select name="id_pejabat">
						<?php foreach($this->pejabat as $data): ?>
						<option value="<?php echo $this->escape($data->id_pejabat); ?>"><?php echo $this->escape($data->nip_pejabat); ?> | <?php echo $this->escape($data->nama_pejabat); ?></option>
						 <?php endforeach; ?>
						</select>
					</td>					
				</tr>
				<tr>
					<td>Keperluan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="keperluan" value="" placeholder="" required/></td>
				</tr>
				<tr>
					<td>Keterangan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="ket" value="" placeholder="keterangan"/></td>
				</tr>
			</table>
				<input class="button" type="submit" name="name" value="Proses" />
				<input class="reset" type="reset" name="reset" value="Ulangi" />
				<input action="action" class="kembali"  value="Kembali" onclick="history.go(-1);" />
			 </div>
		</form>
		<?php
		}else{
			echo "<h4>Penduduk Belum terdaftar</h4>";
		
		?>
			<h7><a href="<? echo $this->basePath;?>/surat/index/tambahpenduduk"> daftarkan</a></h7>
		<?php } ?>
		<br><br><br>
      </div>
	 </div>
	
   <? include "footer.phtml"; ?>

 