<?php	
	ob_start();
	//Format Tanggal Berbahasa Indonesia 

	// Array Hari
	$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
	$hari = $array_hari[date('N')];

	//Format Tanggal 
	$tanggal = date ('j');

	//Array Bulan 
	$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
	$bulan = $array_bulan[date('n')];
	 
	//Format Tahun 
	$tahun = date('Y');

	 
	// Include the PHPWord.php, all other classes were loaded by an autoloader
	include '../etc/libs/PHPWord.php';

	// Create a new PHPWord Object
	$PHPWord = new PHPWord();
		
		
	$document = $PHPWord->loadTemplate('../etc/data/template/KetAjbTemplate.docx');
	//header
	$document->setValue('kecamatan', $this->hasil->kecamatan);
	$document->setValue('kelurahan', $this->hasil->kelurahan);
	$document->setValue('alamat_kelurahan', $this->hasil->alamat_kelurahan);
	
	//isi surat
	//data penduduk awal
	$no_surat = substr($this->hasil->no_registrasi,-3);
	$document->setValue('noSurat',$no_surat);
	$document->setValue('noSuratpengantar', $this->hasil->no_surat_pengantar);
	
	//yang beda2
	$document->setValue('luasTanah', $this->hasil->luas_tanah);
	$document->setValue('luasBangunan', $this->hasil->luas_bangunan);	
	$document->setValue('noPersil', $this->hasil->no_persil);		
	$document->setValue('noKohir', $this->hasil->no_kohir);		
	$document->setValue('blokTanah', $this->hasil->blok_tanah);		
	$document->setValue('rtTanah', $this->hasil->rt_tanah);		
	$document->setValue('rwTanah', $this->hasil->rw_tanah);		
	$document->setValue('kelTanah', $this->hasil->kel_tanah);		
	$document->setValue('kecTanah', $this->hasil->kec_tanah);		
	$document->setValue('noAkta', $this->hasil->no_akta);		
	$document->setValue('namaPemilik', $this->hasil->nama_pemilik);		
	$document->setValue('alamatPemilik', $this->hasil->alamat_pemilik);		
	$document->setValue('pekerjaanPemilik', $this->hasil->pekerjaan_pemilik);		
	$document->setValue('batasUtara', $this->hasil->batas_utara);		
	$document->setValue('batasBarat', $this->hasil->batas_barat);		
	$document->setValue('batasSelatan', $this->hasil->batas_selatan);		
	$document->setValue('batasTimur', $this->hasil->batas_timur);		
	$document->setValue('noPbb', $this->hasil->no_pbb);		
	$document->setValue('hargaTanah',number_format($this->hasil->harga_tanah, 0, ',', '.'));
	$document->setValue('hargaBangunan',number_format($this->hasil->harga_bangunan, 0, ',', '.'));
	
	$hasil_tanah = $this->hasil->luas_tanah * $this->hasil->harga_tanah;
	$document->setValue('hasilTanah',number_format($hasil_tanah, 0, ',', '.'));
	
	$hasil_bangunan = $this->hasil->luas_bangunan * $this->hasil->harga_bangunan;
	$document->setValue('hasilBangunan', number_format($hasil_bangunan, 0, ',', '.'));
	
	$jumlah = $hasil_tanah + $hasil_bangunan;	
	$document->setValue('jumlah', number_format($jumlah, 0, ',', '.'));	
	
	$document->setValue('keperluan', $this->hasil->keperluan);		
				
	//titimangsa surat
	$document->setValue('titimangsa',$tanggal ." ". $bulan ." ". $tahun);
	$document->setValue('namaPejabat', $this->hasil->nama_pejabat);
	$document->setValue('nipPejabat', $this->hasil->nip_pejabat);
	
	$path='E:\\';
	
	$namafile = "KetAJB_".$this->hasil->nama."_"."_".date('Y-m-d').".docx";
	// $document->save('E:\\andonnikahTemplate.docx');
	//$document->save('E:\\'.$nama_file);
	
	
	// At least write the document to webspace:
	$objWriter = PHPWord_IOFactory::createWriter($PHPWord, 'Word2007');
	
	// // save as a random file in temp file
	$temp_file = tempnam(sys_get_temp_dir(), 'PHPWord');
	$document->save($temp_file);
	
	// Your browser will name the file "myFile.docx"
	// regardless of what it's named on the server 
	
	header('Content-Disposition: attachment; filename="' . $namafile . '"');
	header('Content-Transfer-Encoding: binary');
	header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
	header('Expires: 0');
	header('Pragma: public');
	flush();
	readfile($temp_file); // or echo file_get_contents($temp_file);
	unlink($temp_file);  // remove temp file
	exit;
?>