<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		<?php
			if($this->hasil){
		?>
		<form id="form1" action="<? echo $this->basePath;?>/surat/index/simpanprosesktbajbedit?id_permintaan_ajb=<?php echo $this->hasil->id_permintaan_ajb; ?>" method="post">
		<div class="form_settings2">
			
			<table id="rounded-corner">
				<tr>
					<td>NIK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nik" value="<?php echo $this->hasil->nik; ?>" placeholder="" readonly /></td>
				</tr>
				<tr>
					<td>Nama</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama" value="<?php echo $this->hasil->nama; ?>" placeholder="" readonly /></td>
				</tr>
				
				
				<tr>
					<td>Nomor Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat" value="<?php echo $this->hasil->no_surat; ?>" placeholder="" readonly/></td>
				</tr>
				<tr>
					<td>Tanggal Surat</td>
					<td>:</td>
					<td><input width="1px" type="date" name="tanggal_surat" value="<?php echo $this->hasil->tanggal_surat; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Nomor Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat_pengantar" value="<?php echo $this->hasil->no_surat_pengantar; ?>" placeholder=""/>
					&nbsp &nbsp RT &nbsp &nbsp
					<input width="0" type="kecil" name="rt" value="<?php echo $this->hasil->rt; ?>" placeholder=""/>
					<input width="0" type="kecil" name="rw" value="<?php echo $this->hasil->rw; ?>" placeholder=""/>
					</td>
				</tr>
				<tr>
					<td>Tanggal Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="date" name="tanggal_surat_pengantar" value="<?php echo $this->hasil->tanggal_surat_pengantar; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Keperluan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="keperluan" value="<?php echo $this->hasil->keperluan; ?>" placeholder="" required/></td>
				</tr>
				<tr>
					<td colspan="3">Detail Tanah dan Bangunan</td>
					
				</tr>

				<tr>
					<td>NIK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nik" value="<?php echo $this->hasil->nik; ?>" placeholder="" readonly /></td>
				</tr>
				<tr>
					<td>Nama Pemilik</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_pemilik" value="<?php echo $this->hasil->nama; ?>" placeholder="" required /></td>
				</tr>				
				<tr>
					<td>Alamat Pemilik</td>
					<td>:</td>
					<td><textarea name="alamat_pemilik" required ><?php echo $this->hasil->alamat; ?></textarea></td>
				</tr>				
				
				<tr>
					<td>Pekerjaan Pemilik</td>
					<td>:</td>
					<td><input width="1px" type="text" name="pekerjaan_pemilik" value="<?php echo $this->hasil->pekerjaan; ?>" placeholder="pekerjaan"  /></td>
				</tr>
				<tr>
					<td>Luas tanah</td>
					<td>:</td>
					<td><input width="1px" type="text" name="luas_tanah" value="0" placeholder="luas tanah" required digits="true"/> M<sup>2</sup></td>
				</tr>
				<tr>
					<td>Luas Bangunan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="luas_bangunan" value="0" placeholder="luas bangunan" required  digits="true" /> M<sup>2</sup></td>
				</tr>
				<tr>
					<td>Nomor Persil</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_persil" value="" placeholder="nomor persil" required /></td>
				</tr>
				<tr>
					<td>Nomor Kohir</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_kohir" value="" placeholder="nomor kohir" required  /></td>
				</tr>				
				<tr>
					<td colspan="3">Alamat Tanah</td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Blok </td>
					<td>:</td>
					<td><input width="1px" type="text" name="blok_tanah" value="" placeholder="blok tanah"  required/></td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;RT / RW</td>
					<td>:</td>
					<td><input width="1px" type="kecil" name="rt_tanah" value="" placeholder="RT" required /> <input width="1px" type="kecil" name="rw_tanah" value="" placeholder="RW" required /></td>
				</tr>
				
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kelurahan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="kel_tanah" value="Leuwigajah" placeholder="kelurahan" required /></td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kecamatan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="kec_tanah" value="Cimahi Selatan" placeholder="kecamatan" required /></td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nomor Akta</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_akta" value="" placeholder="nomor akta tanah" required /></td>
				</tr>
				
				<tr>
					<td colspan="3">Batas</td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Utara</td>
					<td>:</td>
					<td><input width="1px" type="text" name="batas_utara" value="" placeholder="batas utara" required /> </td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Barat</td>
					<td>:</td>
					<td><input width="1px" type="text" name="batas_barat" value="" placeholder="batas barat" required /> </td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Selatan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="batas_selatan" value="" placeholder="batas selatan" required /> </td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Timur</td>
					<td>:</td>
					<td><input width="1px" type="text" name="batas_timur" value="" placeholder="batas timur" required /> </td>
				</tr>
				
				<tr>
					<td>Nomor PBB</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_pbb" value="" placeholder="nomor pbb" required /> </td>
				</tr>
				<tr>
					<td>Harga Tanah per M<sup>2</sup></td>
					<td>:</td>
					<td><input width="1px" type="text" name="harga_tanah" value="0" placeholder="harga tanah" required digits="true" /> </td>
				</tr>
				<tr>
					<td>Harga Bangunan M<sup>2</sup></td>
					<td>:</td>
					<td><input width="1px" type="text" name="harga_bangunan" value="0" placeholder="harga bangunan" required  digits="true"/> </td>
				</tr>

				<tr>
					<td>Mengetahui</td>
					<td>:</td>
					<td><select name="id_pejabat">
						<?php foreach($this->pejabat as $data): ?>
						<option value="<?php echo $this->escape($data->id_pejabat); ?>"><?php echo $this->escape($data->nip_pejabat); ?> | <?php echo $this->escape($data->nama_pejabat); ?></option>
						 <?php endforeach; ?>
						</select>
					</td>					
				</tr>	
				
			</table>
				
				<input class="button" type="submit" name="name" value="ubah" />
			 </div>
		</form>
		<?php
		}else{
			echo "<h4>Penduduk Belum terdaftar</h4>";
		
		?>
			<h7><a href="<? echo $this->basePath;?>/surat/index/tambahpenduduk"> daftarkan</a></h7>
		<?php } ?>
		<br><br><br>
      </div>
	 </div>
	
   <? include "footer.phtml"; ?>