<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		<?php
			if($this->hasil){
		?>
		<form action="<? echo $this->basePath;?>/surat/index/simpanpermintaanlahiredit?id_permintaan_lahir=<?php echo $this->hasil->id_permintaan_lahir; ?>" method="post">
		<div class="form_settings2">
			
			<table>
				<tr>
					<td>NIK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nik" value="<?php echo $this->hasil->nik; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Nama</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama" value="<?php echo $this->hasil->nama; ?>" placeholder=""/></td>
				</tr>
				
					<td>Nomor Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat" value="<?php echo $this->hasil->no_surat; ?>" placeholder=""/ onclick="alert=('nomer surat tidak boleh sama')"></td>
				</tr>
				<tr>
					<td>Tanggal Surat</td>
					<td>:</td>
					<td><input width="1px" type="date" name="tanggal_surat" value="<?php echo $this->hasil->tanggal_surat; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>Nomor Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat_pengantar" value="<?php echo $this->hasil->no_surat_pengantar; ?>" placeholder=""/>
					&nbsp &nbsp RT &nbsp &nbsp
					<input width="0" type="text" name="rt" value="<?php echo $this->hasil->rt; ?>" placeholder=""/>
					</td>
				</tr>
				<tr>
					<td>Tanggal Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="date" name="tanggal_surat_pengantar" value="<?php echo $this->hasil->tanggal_surat_pengantar; ?>" placeholder=""/></td>
				</tr>
				<tr>
					<td>NIP Pejabat Kelurahan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nip_pejabat" value="<?php echo $this->hasil->nip_pejabat; ?>" placeholder="" readonly /></td>
				</tr>
				<tr>
					<td>Nama Pejabat Kelurahan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_pejabat" value="<?php echo $this->hasil->nama_pejabat; ?>" placeholder="" readonly /></td>
				</tr>				
			</table>
			<h4>DATA ANAK</h4>
			<table>
				<tr>
					<td>Nama Anak</td>
					<td>:</td>
					<td><input type="text" name="nama_anak" value="<?php echo $this->hasil->nama_anak; ?>" placeholder=""/> </td>
				</tr>
				<tr>
					<td>Jenis kelamin</td>
					<td>:</td>
					<td><select name="jenis_kelamin_anak">
						<option value="<?php echo $this->hasil->jenis_kelamin_anak; ?>"><?php echo $this->hasil->jenis_kelamin_anak; ?></option>
						<option value="Perempuan">Perempuan</option>
						<option value="Laki">Laki-laki</option>
					</select> 
					</td>
				</tr>
				<tr>
					<td>Tempat/Tanggal Lahir</td>
					<td>:</td>
					<td><input type="text" name="tempat_lahir_anak" value="<?php echo $this->hasil->tempat_lahir_anak; ?>" placeholder="" /> &nbsp /&nbsp <input width="1px" type="date" name="tgl_lahir_anak" value="<?php echo $this->hasil->tgl_lahir_anak; ?>" placeholder="" /></td>
				</tr>
				<tr>
					<td>Anak Ke</td>
					<td>:</td>
					<td><select name="anak_ke">
						<option value="<?php echo $this->hasil->anak_ke; ?>"><?php echo $this->hasil->anak_ke; ?></option>
						<option value="1">1</option>
						<option value="1">2</option>
						<option value="2">3</option>
						<option value="3">4</option>
						<option value="4">5</option>
						<option value="5">6</option>
						<option value="6">7</option>
					</select> 
					</td>
				</tr>
				<tr>
					<td>Jam Lahir</td>
					<td>:</td>
					<td><input type="text" name="jam_lahir" value="<?php echo $this->hasil->jam_lahir; ?>" required/>
					</td>
				</tr>
			</table>
				
				<input class="button" type="submit" name="name" value="ubah" />
			 </div>
		</form>
		<?php
		}else{
			echo "<h4>Penduduk Belum terdaftar</h4>";
		
		?>
			<h7><a href="<? echo $this->basePath;?>/surat/index/tambahpenduduk"> daftarkan</a></h7>
		<?php } ?>
		<br><br><br>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>