<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		<?php
			if($this->hasil){
		?>
		<form action="<? echo $this->basePath;?>/surat/index/simpanprosesnaedit?id_permintaan_na=<?php echo $this->hasil->id_permintaan_na; ?>" method="post">
		<div class="form_settings2">
			
			<input width="1px" type="hidden" name="id_permintaan_na" value="<?php echo $id_permintaan_na; ?>" placeholder="" readonly />
			<input width="1px" type="hidden" name="id_jenis_surat" value="<?php echo $this->getSurat->id_jenis_surat; ?>" placeholder="" readonly />
			<input width="1px" type="hidden" name="id_surat" value="<?php echo $this->getSurat->id_surat; ?>" placeholder="" readonly />
			<table id="rounded-corner">
				<tr>
					<td>No Registrasi</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_registrasi" value="<?php echo $this->no_registrasi; ?>" placeholder="" readonly /></td>
				</tr>
				<tr>
					<td>NIK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nik" value="<?php echo $this->hasil->nik; ?>" placeholder="" readonly /></td>
				</tr>
				<tr>
					<td>Nama</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama" value="<?php echo $this->hasil->nama; ?>" placeholder="" readonly /></td>
				</tr>
				<tr>
					<td>Nomor KK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_kk" value="<?php echo $this->hasil->no_kk; ?>" placeholder="" readonly /></td>
				</tr>
				<tr>
					<td>Alamat</td>
					<td>:</td>
					<td><textarea name="alamat" readonly ><?php echo $this->hasil->alamat; ?></textarea></td>
				</tr>
				<tr>
					<td>Tempat/Tanggal Lahir</td>
					<td>:</td>
					<td><input width="1px" type="text" name="tempat_lahir" value="<?php echo $this->hasil->tempat_lahir; ?>" placeholder="" readonly /> &nbsp /&nbsp <input width="1px" type="text" class="tanggal" name="tanggal_lahir" value="<?php echo $this->hasil->tanggal_lahir; ?>" placeholder="" readonly /></td>
				</tr>
				<tr>
					<td>Agama</td>
					<td>:</td>
					<td><input type="text" name="agama" value="<?php echo $this->hasil->agama; ?>"  readonly />	</td>
				</tr>
				<tr>
					<td>Jenis Kelamin</td>
					<td>:</td>
					<td><input type="text" name="jenis_kelamin" value="<?php echo $this->hasil->jenis_kelamin; ?>"  readonly />	</td>
					</td>
				</tr>
				<tr>
					<td>Pekerjaan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="pekerjaan" value="<?php echo $this->hasil->pekerjaan; ?>" placeholder="" readonly /></td>
				</tr>
				<tr>
					<td>Nomor Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat" value="<?php echo $this->getSurat->kode_surat?> / <?php echo $this->no_registrasi?> / <?php echo $this->KodeKelurahan; ?>" placeholder="" required/></td>
				</tr>
				<tr>
					<td>Tanggal Surat</td>
					<td>:</td>
					<td><input width="1px" type="text" class="tanggal" name="tanggal_surat" value="<? echo date('Y-m-d');?>" placeholder="" required/></td>
				</tr>
				<tr>
					<td>Nomor Surat Pengantar*<br/> wajib diisi</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_surat_pengantar" value="<?php echo $this->hasil->no_surat_pengantar; ?>" placeholder="" class="required remote" minlength="4"/>
					&nbsp &nbsp RT / RW &nbsp &nbsp
					<input width="0" type="kecil" class="kecil" name="rt" value="<?php echo $this->hasil->rt; ?>" placeholder="" readonly /> &nbsp /&nbsp
					<input width="1px" type="kecil" class="kecil"  name="rw" value="<?php echo $this->hasil->rw; ?>" placeholder="" readonly />
					</td>
				</tr>
				<tr>
					<td>Tanggal Surat Pengantar</td>
					<td>:</td>
					<td><input width="1px" type="text" class="tanggal" id="tanggal" name="tanggal_surat_pengantar" value="<?php echo $this->hasil->tanggal_surat_pengantar; ?>" placeholder="" required/></td>
				</tr>
				<tr>
				
				<tr>
					<td>Nama Istri</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_istri"  minlength="2" value="<?php echo $this->hasil->nama_istri; ?>" placeholder="" required/></td>
				</tr>
				<tr>
					<td>Nama Ayah</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_ayah"  minlength="2" value="<?php echo $this->hasil->nama_ayah; ?>" placeholder="" required/></td>
				</tr>
				
				<tr>
					<td>Nama Ibu</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_ibu"  minlength="2" value="<?php echo $this->hasil->nama_ibu; ?>" placeholder="" required/></td>
				</tr>
				<tr>
					<td>Mengetahui</td>
					<td>:</td>
					<td><select name="id_pejabat">
						<?php foreach($this->pejabat as $data): ?>
						<option value="<?php echo $this->escape($data->id_pejabat); ?>" <?php if( $this->escape($data->id_pejabat) == $this->hasil->id_pejabat?> selected > <?php echo $this->escape($data->nip_pejabat); ?> | <?php echo $this->escape($data->nama_pejabat); ?></option>
						 <?php endforeach; ?>
						</select>
					</td>					
				</tr>
				<tr>
					<td>Keterangan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="ket" value="" placeholder="keterangan"/></td>
				</tr>
			</table>
				<input class="button" type="submit" name="name" value="Proses" />
				<input class="reset" type="reset" name="reset" value="Ulangi" />
				<input action="action" class="kembali"  value="Kembali" onclick="history.go(-1);" />
			 </div>
		</form>
		<?php
		}else{
			echo "<h4>Penduduk Belum terdaftar</h4>";
		
		?>
			<h7><a href="<? echo $this->basePath;?>/surat/index/tambahpenduduk"> daftarkan</a></h7>
		<?php } ?>
		<br><br><br>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>