<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		Pencarian
		<form action="<? echo $this->basePath;?>/surat/index/pencarianmati" method="post">
		<div class="form_settings2">
				<select name="id_pencarian">
					<option value="1">No.Surat</option>
					<option value="2">NIK</option>
				</select>
				<input width="1px" type="text" name="pencarian" value="<? echo $this->cari; ?>" placeholder=""/>
				<input class="submit" type="submit" name="name" value="cari" />
			 </div>
		</form><br>
		<form action="<? echo $this->basePath;?>/surat/index/caripendudukmati" method="post">
		<div class="form_settings2">
				<button class="button">tambah permintaan</button>
			 </div>
		</form><br>
		
		<table style="width:100%; border-spacing:0;">
          <tr align ="center">
			  <th>No</th>
			  <th>No Surat</th>
			  <th>Tgl Surat</th>
			  <th>NIK</th>
			  <th>RT</th>
			  <th colspan=3>Aksi</th>
		  </tr>
		 <?php $i=1; foreach($this->permintaan as $data) : ?>
			<tr>
			<td><?php echo $i;?></td>		
            <td><?php echo $this->escape($data->no_surat);?></td>
            <td><?php echo $this->escape($data->tanggal_surat);?></td>
            <td><?php echo $this->escape($data->nik);?></td>
            <td><?php echo $this->escape($data->rt);?></td>
           
			
			
            <td><a href="<?php echo $this->basePath; ?>/surat/index/matiedit?id_permintaan_mati=<?php echo $this->escape($data->id_permintaan_mati);?>"><img src="<? echo $this->basePath;?>/images/user_edit.png" alt="" title="edit" border="0" /></a></td>
            <td><a href="<?php echo $this->basePath; ?>/surat/index/matihapus?id_permintaan_mati=<?php echo $this->escape($data->id_permintaan_mati);?>" class="ask"><img src="<? echo $this->basePath;?>/images/trash.png" alt="" title="hapus" border="0" /></a></td>
			<?php if ($data->status==1){?>
			 <td><a href="http://127.0.0.1:62086/viewer/frameset?__report=D%3A%5CProject%5Cworkspace%5Csimkelurahan%5Cmati.rptdesign&__format=pdf&__svg=false&__locale=en_US&__timezone=Asia%2FBangkok&__masterpage=true&__rtl=false&__cubememsize=10&__resourceFolder=D%3A%5CProject%5Cworkspace%5Csimkelurahan&__dpi=96&-312322503&id_kelurahan=<? echo $this->kelurahan;?>&id_permintaan=<? echo $data->id_permintaan_mati; ?>" target ="_blank" ><img src="<? echo $this->basePath;?>/images/photo.png" alt="" title="cetak" border="0" /></a></td>
			<?php } ?>
		
			
        </tr>
		<?php $i++; endforeach; ?>
          
        </table>
      </div>
	 </div>
	
   <?//include "footer.phtml"; ?>