<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		<form id="form1" action="<? echo $this->basePath;?>/surat/index/simpanpendudukedit" method="post">
		<div class="form_settings2">
			<table>
				<tr>
					<td>Nomor KK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_kk" value="<?php echo $this->hasil->no_kk?>" placeholder="silakan masukan nomor KK" required /></td>
				</tr>
				<tr>
					<td>Nama Kepala Keluarga</td>
					<td>:</td>
					<td><input width="1px" type="nama_kep" name="nama_kep" value="<?php echo $this->hasil->nama_kep?>" placeholder="silakan masukan Nama Kepala Keluarga" required /></td>
				</tr>
				<tr>
					<td>Alamat</td>
					<td>:</td>
					<td><textarea name="alamat"  rows="4" cols="35"><?php echo $this->hasil->alamat?></textarea>
					&nbsp &nbsp RT / RW &nbsp &nbsp
					<input  width="20px" type="kecil" name="rt" value="<?php echo $this->hasil->rt?>" placeholder="rt"/> &nbsp /&nbsp
					<input  width="20px" type="kecil" name="rw" value="<?php echo $this->hasil->rw?>" placeholder="rw"/></td>
				</tr>
				<tr>
					<td>Dusun</td>
					<td>:</td>
					<td><input width="1px" type="text" name="dusun" value="<?php echo $this->hasil->dusun?>" placeholder="dusun" required /></td>
				</tr>
				<tr>
					<td>Kode POS</td>
					<td>:</td>
					<td><input width="1px" type="text" name="kode_pos" value="<?php echo $this->hasil->kode_pos?>" placeholder="silakan masukan kode pos" required/></td>
				</tr>
				<tr>
					<td>NIK</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nik" value="<?php echo $this->hasil->nik?>" placeholder="silakan masukan NIK" readonly/></td>
				</tr>
				<tr>
					<td>Nama Lengkap</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_lengkap" value="<?php echo $this->hasil->nama_lengkap?>" placeholder="silakan masukan Nama Lengkap" required/></td>
				</tr>
				<tr>
					<td>Jenis Kelamin</td>
					<td>:</td>
					<td>
						<select name="jk">
							<option value="<?php echo $this->hasil->jenis_kelamin ?>" selected><?php echo $this->hasil->jenis_kelamin?></option>
							<option value="Laki-laki">Laki-laki</option>
							<option value="Perempuan">Perempuan</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Tempat/Tanggal Lahir</td>
					<td>:</td>
					<td><input width="1px" type="text" name="tempat_lahir" value="<?php echo $this->hasil->tempat_lahir?>" placeholder="tempat kelahiran" required/> &nbsp /&nbsp <input width="1px" type="text" class="tanggal" name="tanggal_lahir" value="<?php echo $this->hasil->tanggal_lahir?>" placeholder="tanggal lahir" required/></td>
				</tr>
				<tr>
					<td>Nomor Akta</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_akta" value="<?php echo $this->hasil->no_akta?>" placeholder="silakan masukan Nomor Akta" required/></td>
				</tr>
				<tr>
					<td>Golongan Darah</td>
					<td>:</td>
					<td>
						<select name="gol_darah">
							<option value="<?php echo $this->hasil->gol_darah?>"><?php echo $this->hasil->gol_darah?></option>
							<option value="O">O</option>
							<option value="A">A</option>
							<option value="B">B</option>
							<option value="AB">AB</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Agama</td>
					<td>:</td>
					<td>
						<select name="agama">
							<option value="<?php echo $this->hasil->agama?>"><?php echo $this->hasil->agama?></option>
							<option value="Islam">Islam</option>
							<option value="Budha">Budha</option>
							<option value="Hindu">Hindu</option>	
							<option value="Kristen Katolik">Kristen Katolik</option>
							<option value="Kristen Protestan">Kristen Protestas</option>
						</select>
					</td>
				</tr>
				
				<tr>
					<td>Pekerjaan</td>
					<td>:</td>
					<td><input width="1px" type="text" name="pekerjaan" value="<?php echo $this->hasil->pekerjaan?>" placeholder="silakan masukan Pekerjaan" required/></td>
				</tr>
				<tr>
					<td>Nama Ibu</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_ibu" value="<?php echo $this->hasil->nama_ibu?>" placeholder="nama ibu" required/></td>
				</tr>
				<tr>
					<td>Nama Ayah</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama_ayah" value="<?php echo $this->hasil->nama_ayah?>" placeholder="nama ayah" required/></td>
				</tr>
				<tr>
					<td>Status Perkawinan</td>
					<td>:</td>
					<td>
						<select name="status_perkawinan">
							<option value="<?php echo $this->hasil->status_perkawinan?>"><?php echo $this->hasil->status_perkawinan?></option>
							<option value="Menikah">Menikah</option>
							<option value="Belum Menikah">Belum Menikah</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>kelurahan</td>
					<td>:</td>
					<td>
						<select name="id_kelurahan">
						<?php foreach($this->kelurahan as $data) : ?>
							<option value="<?php echo $data->id_kelurahan; ?>"><?php echo $data->nama_kelurahan; ?></option>
						<? endforeach; ?>
						</select>
					</td>
				</tr>
				
			</table>
				
				<input class="button" type="submit" name="name" value="Simpan" />
				<input class="reset" type="reset" name="reset" value="Ulangi" />
				<input action="action" class="kembali"  value="Batal" onclick="history.go(-1);" />
			 </div>
		</form>
		<br><br><br>
      </div>
	 </div>
	
<?include "footer.phtml"; ?>