<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<?// include "barkanan.phtml"; ?>
      <div id="contentadmin">
        <h1><?php echo $this->surat;?></h1>
		
		<div class="form_settings2">
		<form action="<? echo $this->basePath;?>/surat/index/simpanpenelitianantrian" method="post">
			<table id="rounded-corner">		
				<tr>
					<td>No. Registrasi</td>
					<td>:</td>
					<td><input width="1px" type="text" name="no_registrasi" value="<?php echo $this->no_registrasi; ?>" readonly/></td>
				</tr>
				<tr>
					<td>NIM</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nim"  value="<?php echo $this->hasil->nim; ?>" required/></td>
				</tr>
				<tr>
					<td>Nama</td>
					<td>:</td>
					<td><input width="1px" type="text" name="nama"  value="<?php echo $this->hasil->nama; ?>" required/></td>
				</tr>
				<tr>
					<td>Jurusan / Prodi</td>
					<td>:</td>
					<td><input width="1px" type="text" name="jurusan"  value="<?php echo $this->hasil->jurusan; ?>" required/></td>
				</tr>
				<tr>
					<td>Universitas</td>
					<td>:</td>
					<td><input width="1px" type="text" name="universitas"  value="<?php echo $this->hasil->universitas; ?>" required/></td>
				</tr>
				
				<tr>
					<td>No Telp</td>
					<td>:</td>
					<td><input type="text" name="no_telp"  value="" required/></td>
				</tr>	
				<input class="button" type="submit" name="name" value="simpan antrian" />
			</form>
			</div>
		<?php ?>
		
		<br><br><br>
      </div>
