<? include "header.phtml"; ?>
<? include "menubar.phtml"; ?>
<?// include "barkanan.phtml"; ?>
     
	 <div id="contentadmin">
        <h1>Edit Profil Pengguna</h1>
			<form id="form1" action="<? echo $this->basePath;?>/surat/index/simpanpenggunaedit?id_pengguna=<?php echo $this->pengguna->id_pengguna;?>" method="post">
			  <div class="form_settings">
				
				<input type="hidden" name="id_pengguna"  value="<?php echo $this->pengguna->id_pengguna; ?>"/>
				<input type="hidden" name="id_data_pegawai"  value="<?php echo $this->pengguna->id_data_pegawai; ?>"/>
				<input type="hidden" name="id_jenis_pengguna"  value="<?php echo $this->pengguna->id_jenis_pengguna; ?>"/>
				
				<br><br>Kelurahan : <br><input type="text" name="nama_kelurahan" value="<?php echo $this->pengguna->nama_kelurahan;?>" readonly/><br>
				<input type="hidden" name="id_kelurahan" value="<?php echo $this->pengguna->id_kelurahan;?>" readonly/>
				
				<br><br>Nama Pengguna :<br>
				<input type="text" name="nama_pengguna" value="<?php echo $this->pengguna->nama_pengguna;?>" placeholder="masukan nama pengguna" required/>
				
				<br><br>NIP Pengguna :<br>
				<input type="text" name="nip_pengguna" value="<?php echo $this->pengguna->nip_pengguna;?>" placeholder="masukan nip pengguna" required/>
				
				<br><br>Jabatan<br>
				<input type="text" name="jabatan" value="<?php echo $this->pengguna->jabatan;?>" placeholder="masukan nip pengguna"/>
				
				<br><br>Alamat :<br>
				<input type="text" name="alamat" value="<?php echo $this->pengguna->alamat;?>" placeholder="masukan alamat pengguna" required/>
				
				<br><br>Nomor Telp :<br>
				<input type="text" name="no_telp" value="<?php echo $this->pengguna->no_telp;?>" placeholder="masukan no_telp pengguna" required/>
				
				<br><br>Username :<br>
				<input type="text" name="username" value="<?php echo $this->pengguna->username;?>" placeholder="masukan username" required/>
				
				<br><br>Password :<br>
				<input type="password" name="password" value="<?php echo $this->pengguna->password;?>" placeholder="masukan password" required/>
				<br><br>
				
				<input class="button" type="submit" name="name" value="Ubah" />
				<input class="reset" type="reset" name="reset" value="Ulangi" />
				<input action="action" class="kembali"  value="Kembali" onclick="history.go(-1);" />
			  </div>
			</form><br><br></center>
      </div>
	 </div>
	
   <? include "footer.phtml"; ?>