<?php
	
	//Format Tanggal Berbahasa Indonesia 

	// Array Hari
	$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
	$hari = $array_hari[date('N')];

	//Format Tanggal 
	$tanggal = date ('j');

	//Array Bulan 
	$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
	$bulan = $array_bulan[date('n')];
	 
	//Format Tahun 
	$tahun = date('Y');

	 
	// Include the PHPWord.php, all other classes were loaded by an autoloader
	include '../etc/libs/PHPWord.php';

	// Create a new PHPWord Object
	$PHPWord = new PHPWord();
		
		
	$document = $PHPWord->loadTemplate('../etc/data/template/RumahSakitTemplate.docx');
	//header
	$document->setValue('kecamatan', $this->hasil->kecamatan);
	$document->setValue('kelurahan', $this->hasil->kelurahan);
	$document->setValue('alamat_kelurahan', $this->hasil->alamat_kelurahan);
	
	//isi surat
	//data penduduk awal
	$no_surat = substr($this->hasil->no_registrasi,-3);
	$document->setValue('noSurat',$no_surat);
	$document->setValue('nama', $this->hasil->nama);
	$document->setValue('nik', $this->hasil->nik);
	$document->setValue('tempatLahir', $this->hasil->tempat_lahir);
	
	$tgl_lahir = date('d-m-Y', strtotime($this->hasil->tanggal_lahir ));
	$document->setValue('tanggalLahir', $tgl_lahir);

	$document->setValue('jenisKelamin', $this->hasil->jenis_kelamin);
	$document->setValue('agama', $this->hasil->agama);
	$document->setValue('status', $this->hasil->status);
	$document->setValue('kewarganegaraan', $this->hasil->kewarganegaraan);
	$document->setValue('pekerjaan', $this->hasil->pekerjaan);
	$document->setValue('alamat', $this->hasil->alamat_warga);
	$document->setValue('rt', $this->hasil->rt);
	$document->setValue('rw', $this->hasil->rw);
	$document->setValue('noSuratpengantar', $this->hasil->no_surat_pengantar);
	
	$tanggal_surat_pengantar = date('d-m-Y', strtotime($this->hasil->tanggal_surat_pengantar ));
	$document->setValue('tanggalSuratpengantar', $tanggal_surat_pengantar);
	
	//yang beda2
	$document->setValue('noKk', $this->hasil->no_kk);
	$document->setValue('noJamkesmas', $this->hasil->no_jamkesmas);
	$document->setValue('peruntukan', $this->hasil->peruntukan);		
	$document->setValue('masaBerlaku', $this->hasil->masa_berlaku);		
	$document->setValue('namaRumahSakit', $this->hasil->nama_rumahsakit);		
				
	//titimangsa surat
	$document->setValue('titimangsa',$tanggal ." ". $bulan ." ". $tahun);
	$document->setValue('namaPejabat', $this->hasil->nama_pejabat);
	$document->setValue('nipPejabat', $this->hasil->nip_pejabat);
	
	$path='E:\\';
	
	$namafile = "RUMAHSAKIT_".$this->hasil->nama."_"."_".date('Y-m-d').".docx";
	// $document->save('E:\\andonnikahTemplate.docx');
	//$document->save('E:\\'.$nama_file);
	
	
	// At least write the document to webspace:
	$objWriter = PHPWord_IOFactory::createWriter($PHPWord, 'Word2007');
	
	// // save as a random file in temp file
	$temp_file = tempnam(sys_get_temp_dir(), 'PHPWord');
	$document->save($temp_file);
	
	// Your browser will name the file "myFile.docx"
	// regardless of what it's named on the server 
	
	header('Content-Disposition: attachment; filename="' . $namafile . '"');
	header('Content-Transfer-Encoding: binary');
	header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
	header('Expires: 0');
	header('Pragma: public');
	flush();
	readfile($temp_file); // or echo file_get_contents($temp_file);
	unlink($temp_file);  // remove temp file

	
	
	exit;


?>
